### ISSUE TITLE
deploy rewards manager on rinkeby

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#104]
Includes
deploying:
BeneficiaryVaults
RewardsManager
UniswapRouter
UniswapFactory
MockPOP

and fixtures:
POP/ETH in uniswap
addresses with POP balance

**Comment by RedVeil** [comment]
Done in: https://github.com/popcorndao/workspace/pull/124

These are the contract addresses on rinkeby:
ADDR_TESTNET_BENEFICIARY_REGISTRY=0x650A11b95E346C219f4F11fA9095212e7ccC8120
ADDR_TESTNET_GRANT_REGISTRY=0x8a3d3c94dE1a47604e481243b322c05Ef0Ec26C4
ADDR_TESTNET_POP=0xAF945420315690C0BD867185893F5Cf0355d9273
ADDR_TESTNET_STAKING=0x32f29DB8F03C3aC77AB9070F70aa0640697Df9ac
ADDR_TESTNET_RANDOM_NUMBER=0x9cDC42277D1909a3Bb41D57c1d30A948c7e19c09
ADDR_TESTNET_GOVERNANCE=0x8830Ac7aF80Bbd1F2c040a5b135Ff0d8e080224d
ADDR_TESTNET_TREASURY=0xEDFC72591D7997d5a90f174c0D372414f5163ff2
ADDR_TESTNET_INSURANCE=0x49e7E50316d706b4596EC67aC647acb851B2489c
ADDR_TESTNET_BENEFICIARY_VAULT=0xd2D71F7058b06D00caa4f0793Ee2fD18e974EBAA
ADDR_TESTNET_REWARDS_MANAGER=0x4789C08b352163D425b0a7559Fb17e0f987e5054
ADDR_TESTNET_GRANT_ELECTION=0x71EaBAFbc969c8Eb8E37c7664204B69fA4144712
