### ISSUE TITLE
create integration test for rewards manager

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#116]
An integration test should be written which tests all aspects of the RewardsManager, including: 

1. Uniswap integration (swapping rewards for POP): https://github.com/popcorndao/workspace/blob/main/packages/contracts/contracts/RewardsManager.sol#L138

2. BeneficiaryVault, Treasury and Staking distribution

3. State changes (treasury, etc.)

**Comment by RedVeil** [comment]
Done in https://github.com/popcorndao/workspace/pull/151
