### ISSUE TITLE
distribute POP tokens to voters

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#120]
When voting in grant elections, beneficiary nominations and beneficiary takedown proposals, voters should receive a proportional amount of POP tokens according to their voiceCredits in relation to all of the voiceCredits used in that particular proposal or election. 

*Allocating POP Tokens for Rewards:*
For each proposal and grant election an absolute number of POP tokens will be allocated to be shared with those who have participated in voting for that particular proposal or election. The number of tokens allocated for each proposal/election should be configurable by governance. The reward tokens will be held by each respective contract. For each rewardable proposal/election, there will be a vault created to handle accounting for redeeming the share of POP rewards to the participant. 

* This logic should be contained in an inheritable contract which will be inherited by the GrantElection and BeneficiaryNomination  and BeneficiaryTakedown contracts.
* Addresses may only receive POP token rewards *once* per proposal/election.
* Todo: review RewardsEscrow contract.
* Reference: https://github.com/popcorndao/scaling-eth-hackathon/blob/master/packages/hardhat/contracts/BatchWithdrawablePool.sol#L137

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/172

**Comment by anthonymartin** [comment]
Assigning back to you @RedVeil since tests are failing. 

Also there are a couple other things I'd like for you to address. Can you add a test to ensure a claim can't be made multiple times?

And do you think it's worth revising this vault structure so it more closely resembles the BeneficiaryVaults with regard to claiming rewards? (e.g. that contract has simply sets ` vaults[vaultId_].claimed[beneficiary_] = true;` 

It would make sense to have a uniform design for all the vaults - what do you think?

**Comment by RedVeil** [comment]
New PR https://github.com/popcorndao/workspace/pull/251

**Comment by RedVeil** [comment]
addressed comments
