### ISSUE TITLE
implement token vesting on StakingRewards

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#122]
When tokens are claimed from the rewards contract, they should be vested according to a configurable vesting schedule.

The default schedule is 1/3 released immediately, and 2/3 will be released linearly over 6 months starting after a 3 month lock-up period. 

We should look at existing timelock and vesting contracts to handle this use case. 

https://github.com/Synthetixio/synthetix/blob/develop/contracts/RewardEscrow.sol

**Comment by RedVeil** [comment]
Whats the state on this ticket? Did we decide on a final implementation?

**Comment by anthonymartin** [comment]
@RedVeil and @ecmendenhall - would you 2 be able to sync up on this ticket? I'd like for  @ecmendenhall to review this and get his opinion on the implementation

**Comment by ecmendenhall** [comment]
Sure! Let's sync up on chat. Would be good to sync on #287 and #265 too—we're both starting to overlap there.

**Comment by RedVeil** [comment]
TODO make RewardsEscrow vaults behave like benVaults (Can Vaults be abstracted?)

**Comment by RedVeil** [comment]
rework done and tests updated in https://github.com/popcorndao/workspace/pull/159/commits/f75f6dffcf55671b44fdba188144a340e3139e86

**Comment by anthonymartin** [comment]
left some comments to review. looks great though and much cleaner than before

**Comment by RedVeil** [comment]
adressed comments

**Comment by anthonymartin** [comment]
There are more conflicts here, so I'm assigning back to you @RedVeil
