### ISSUE TITLE
Connect Beneficiary pages to contracts

### ISSUE THREAD

**Issue by mefuru** [popcorndao/workspace#129]

**Comment by mefuru** [comment]
Replace fixtures data with contracts in /beneficiaries pages.

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/165

**Comment by anthonymartin** [comment]
@RedVeil - can you take care of the merge conflicts in this PR?

**Comment by RedVeil** [comment]
@anthonymartin done
