### ISSUE TITLE
💸 Support deposits in 3pool (3CRV)

### ISSUE THREAD

**Issue by yaoandrew** [popcorndao/workspace#135]

**Comment by yaoandrew** [comment]
In order to simplify the pool, we should support deposits/withdrawals in a single stable asset. We can continue to explore supporting multiple assets and denominating in 3Pool tokens.

**Comment by anthonymartin** [comment]
* to accept 1 token: 3CRV

in a separate ticket we'll support other assets using a zapper contract

**Comment by anthonymartin** [comment]
* replace zapper with direct pool interface
* create zapper wrapper contract
* replace DAI references with 3CRV

**Comment by ecmendenhall** [comment]
Closing this in favor of #157 after deciding we can't do this without an answer on whether it's safe to use Curve virtual price to compare LP token prices.
