### ISSUE TITLE
Research: Yearn v2 + 3crv strategy

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/workspace#144]
Research question: Is our 3crv-based multi-vault idea compatible with Yearn V2 and partnerships? (We think probably not)

**Comment by ecmendenhall** [comment]
Specifically need to look at mechanism where we increase amount of `want` tokens. Is it a hard requirement to have to increment that value for the vault itself to accrue value? Or is it possible to increment that in some virtual way?

**Comment by anthonymartin** [comment]
4 hr timebox

**Comment by ecmendenhall** [comment]
Closing along with #135.
