### ISSUE TITLE
frontend: claim rewards from RewardsEscrow, Staking and ParticipationRewards (BeneficiaryGovernance & GrantElections)

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#176]
A frontend should be created where a user can claim POP tokens from the RewardsEscrow, Staking, BeneficiaryGovernance and GrantElection contracts.

**Comment by anthonymartin** [comment]
@mefuru this should be unblocked now

**Comment by Stanley-Okwii** [comment]
Use this layout: https://tailwindui.com/components/application-ui/application-shells/stacked
Based on this page: https://www.convexfinance.com/claim
