### ISSUE TITLE
add multi-language support for contracts

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#181]
BeneficiaryGovernance proposals and grant elections should be assigned to a language. the default language will be English. New languages supported by the contracts must be added by governance. 

A distinct council will be nominated for each language that is enabled in the system. Therefore the correct council address must be retrieved depending on the context of the proposal/election. The onlyCouncil modifier should be adjusted accordingly.

Affects:
@popcorn/app: Contract interactions (Beneficiary Nomination Proposals, Grant Elections)
@popcorn/contracts: BeneficiaryGovernance, GrantElections, CouncilControlled

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/213

**Comment by anthonymartin** [comment]
@RedVeil could you make the change as discussed here: https://github.com/popcorndao/workspace/pull/213
 and also resolve the conflicts?

**Comment by RedVeil** [comment]
Moved BeneficiaryVaults into Region and removed the region logic in BeneficiaryVaults.
Therefore updated constructor of other contracts relying on BeneficiaryVaults and updated tests

**Comment by anthonymartin** [comment]
@RedVeil tests are failing but looks good to merge once you fix that

**Comment by RedVeil** [comment]
Test is fixed. It was actually working as intended but for some reason .to.deep.equal() couldnt recognize that the arrays with nested objects are the same.
