### ISSUE TITLE
Refactor grant elections

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#182]
Key Areas of Refactoring:
* Prevent overwriting previous grant elections - each election should have an id
* Connect grant awardees to beneficiary vaults (create beneficiary vault when grant is awarded)
* Implement a hard limit on votes (Users must submit several vote transactions to prevent out of gas errors) - max 5 at a time?
* Grant Election finalization should happen as a permissioned (and POP incentivized) process using merkle proofs. 
* Grant Election finalization should integrate with BeneficiaryVaults, a BeneficiaryVault should be created with for each grant.

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/198

**Comment by anthonymartin** [comment]
@RedVeil can you handle the merge conflicts in the PR?

**Comment by anthonymartin** [comment]
also, can you respond to this comment from last week? https://github.com/popcorndao/workspace/pull/198/files#r682119875

**Comment by RedVeil** [comment]
merged
