### ISSUE TITLE
create tooltip component

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#184]
A tooltip component should be created (inside storybook). The tooltip should look like a question mark icon in a circle, which when hovered over, will display text that is provided as a prop

**Comment by anthonymartin** [comment]
Here is the design example for the tooltip
![Screen Shot 2021-08-10 at 11.37.16 AM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/dab9e694-fc71-4660-9276-aeacecc23dca)

**Comment by RedVeil** [comment]
I wasnt able to make tailwind with postcss work in storybook which is why i took the component and simply added it to components in package/app

https://github.com/popcorndao/workspace/pull/365

**Comment by RedVeil** [comment]
Exists now also in Storybook
