### ISSUE TITLE
Create frontend for rewardsmanager

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#185]
A frontend should be created for the rewards manager which will:

* Display all of the tokens that the contract holds
* expose a swapTokensForPop functionality that will allow the end user to swap any of the tokens for POP.
* display current exchange rate, expected return amount for tokens when swapped for POP (this should look similar to the uniswap interface)
* expose distributeRewards functionality which will show if a distribution can be made and will allow the end user to call the function. It should show the amount of rewards that will be distributed to each address when the function is called.

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/215

**Comment by anthonymartin** [comment]
sending this back to review the comments I left @RedVeil
