### ISSUE TITLE
Provide keeper incentives for calling rewardsmanager functions

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#186]
The distributeRewards and swapTokensForPop functions should be incentivized with POP rewards that are awarded on a monthly basis. There should be a window of time in which those functions may be called, and when called, the caller of the function should be able to claim POP rewards. 

* The amount of POP rewards should be configurable by governance. 
* A balance of POP tokens from swapping fees into POP should be maintained separately from the balance of POP tokens allocated for keeper incentives.
* Access control should be set to allow only authorized addresses from calling the functions. 
* governance configurable option to allow any address to call these functions should also be made available.

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/203

**Comment by anthonymartin** [comment]
Left comments for review in https://github.com/popcorndao/workspace/pull/203

**Comment by RedVeil** [comment]
TODO merge refactor-grant-elections

**Comment by RedVeil** [comment]
UPDATE no more conflicts with refactor-grant-elections

**Comment by anthonymartin** [comment]
@RedVeil left some more comments to review

**Comment by anthonymartin** [comment]
assigning back to @RedVeil  per discussion on discord
