### ISSUE TITLE
add array of nomination proposals and takedown proposals to BeneficiaryGovernance

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#195]
In order to support more efficient querying, a distinct array for nomination and takedown proposals respectively should be created in the BeneficiaryGovernance contract.

Then the adapter here can be updated to retrieve proposals by type: https://github.com/popcorndao/workspace/pull/190/files#diff-7afa475c510799669d9853d89f176177822a731af27a81baeb6e06476a2563d4

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/207

**Comment by anthonymartin** [comment]
left some comments for review: https://github.com/popcorndao/workspace/pull/207

**Comment by RedVeil** [comment]
adressed in https://github.com/popcorndao/workspace/pull/207/commits/b46c3978b0870f81936e51f40098dccca15acd55
