### ISSUE TITLE
stress test claimRewards in ParticipationRewards

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#196]

**Comment by anthonymartin** [comment]
The `ParticipationRewards.claimRewards` function should have more tests added to ensure that rewards can not be unclaimable.

* e.g. Add 50 vaults that have not been opened, and then another 50 that have been opened. Can the claims still be made?

**Comment by RedVeil** [comment]
added in https://github.com/popcorndao/workspace/pull/172/commits/8b59ea1b39ec8abef04158d7704577151fd02111

(branch feature/reward-voting)
