### ISSUE TITLE
add missing metadata to beneficiary application

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#197]
The beneficiary application should include the following additional fields:

1. website (under links): for the beneficiary's website
2. version: for the version number of the application (the default should be set to 1.0 | string)
3. email for contact

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/217

**Comment by anthonymartin** [comment]
pushing back to you @RedVeil  for minor changes
