### ISSUE TITLE
Replace MockYearn / MockCurve contracts

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#221]
Replace MockYearn / MockCurve contracts with production deployed abis where they don't need to be mocked (e.g. in `lib/SetToken`) and where the mocks are being used in tests, they should be replaced with waffle mocks instead using the production abis

> Not sure I understand this—is this just a shortcut to get access to the contract interface? If so, we should probably split out interfaces for all these dependencies somewhere. I've been thinking it's time to move these inline interfaces out of the contracts anyways.

_Originally posted by @ecmendenhall in https://github.com/popcorndao/workspace/pull/211#discussion_r665521240_

**Comment by anthonymartin** [comment]
* use waffle mocks where applicable

**Comment by anthonymartin** [comment]
@ecmendenhall could you resolve the merge conflicts?

**Comment by ecmendenhall** [comment]
@anthonymartin @RedVeil Rebased!
