### ISSUE TITLE
update beneficiary proposal fixtures

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#225]
The fixtures should be updated as follows:
1. batches of beneficiary nomination proposals and takedown proposals should be created, each targeting different stages: open, challenge period, passed, and failed. 
2. each proposal should have a unique image and application document. (the images, descriptions and beneficiaries can be used from the grant elections fixtures)

**Comment by anthonymartin** [comment]
this line should be removed as part of the PR: https://github.com/popcorndao/workspace/blob/4ed858d24440bc5af7b1ba8bb6ba3909fc8632e7/packages/utils/src/Contracts/BeneficiaryRegistry/BeneficiaryRegistryAdapter.ts#L16

**Comment by mefuru** [comment]
Encountering errors when trying to re-add voting on takedown proposals -> #305
