### ISSUE TITLE
loading page

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#226]
When a new page is loading, a well-designed loading screen should appear. The loading page should have an animation. We'd need to work with Annisha on this design

**Comment by FanFanDAO** [comment]
@anthonymartin We can make this a bounty? Currently, Leon said our pages are relatively fast so it has not been done.

**Comment by FanFanDAO** [comment]
@anthonymartin Loading page design ready
<img width="643" alt="Screen Shot 2021-12-03 at 12 36 35 PM" src="https://user-images.githubusercontent.com/93581054/144596289-28a6bd4c-46df-4c44-9f18-9da82384e237.png">
<img width="148" alt="Screen Shot 2021-12-03 at 12 36 40 PM" src="https://user-images.githubusercontent.com/93581054/144596294-e4e8da46-083c-48c2-a45f-0df3c0e0acf5.png">
Source file: https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2468%3A33882

**Comment by FanFanDAO** [comment]
Refer to the animation here. 
Animation requirement:
-Cat turning
- Popcorns surround the cat and move around the cat in the same clockwise direction
https://popcorn.network/

**Comment by Amiroxoxo** [comment]
I can take this on if we're not giving it as a bounty @FanFanDAO @anthonymartin

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/sweet-caramel/pull/98
preview link: https://deploy-preview-98--sweet-caramel.netlify.app/

**Comment by FanFanDAO** [comment]
Very cute...
