### ISSUE TITLE
updates to proposal form

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#227]
* The inputs should not be displayed in the error state as the default
* The instructions should not be in all caps
* References to beneficiary should be replaced with organization, as it is more understandable and organizations only become eligible beneficiaries after the nomination process.
* Mission statement should be a text area input
* Proof of Ownership: the description should be simple, with an expanded description with a tooltip.
* It should be possible to navigate across the different form sections without having to fill out the information so that the user can see what needs to be filled out in advance. 
* error messages should be displayed to user if image upload fails
* uploading additional images should be optional
* remove maximum file upload restriction for impact reports

![Screen Shot 2021-07-09 at 6.26.05 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/c1271b8c-dd7e-4e70-88ad-e2f6c832976b)

**Comment by mefuru** [comment]
add empty state component https://tailwindui.com/components/application-ui/feedback/empty-states

**Comment by anthonymartin** [comment]
@mefuru could you take a look at the conflicts here: https://github.com/popcorndao/workspace/pull/262
