### ISSUE TITLE
beneficiary governance: UI when user has voted

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#232]
The UI should be updated to indicate when a user has already voted for a proposal. 

If the user has already voted for a proposal, it should show the direction they voted and the button to vote should be hidden.

This affects both takedown and nomination proposals.

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/286

**Comment by anthonymartin** [comment]
left a comment for review here: https://github.com/popcorndao/workspace/pull/286#pullrequestreview-714906307

**Comment by RedVeil** [comment]
Adressed it and fixed merge conflicts
