### ISSUE TITLE
show rpc errors in modal when voting in beneficiary governance

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#233]
When voting for proposals, if there is an RPC error, the response (after the word revert) should be displayed to the user in a single action modal.

For example:

if the message says: `RequestError: Error: VM Exception while processing transaction: revert address already voted for the proposal`

the user would see: `address already voted for the proposal`

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/285
