### ISSUE TITLE
Refactor: BeneficiaryVaults

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#25]
To simplify rewards manager logic and promote separation of responsibilities, we should move the Beneficiary vaults to their own contract. This would mean all claiming would happen on the beneficiary vault side.

The "RewardsManager" might be more aptly named a FeeRouter / FeeDistributor which would be in charge solely for converting deposited fees into POP and routing POP to the final destination.

**Comment by partywave** [comment]
I think `RewardsManager` is still a good name for this contract.
