### ISSUE TITLE
Add events to Zapper

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/workspace#254]
- ZapIn
- ZapOut

**Comment by ecmendenhall** [comment]
- ZapIn
- ZapOut

**Comment by RedVeil** [comment]
added in https://github.com/popcorndao/workspace/pull/193/commits/74f8745022961ea3f87749a543254f2a3cd1170d

**Comment by anthonymartin** [comment]
@RedVeil could you add withdrawal token, deposit token, and deposited/withdrawn (lpTokens/withdrawal vars respectively)

**Comment by RedVeil** [comment]
added in https://github.com/popcorndao/workspace/pull/193/commits/5606a18f278b40143a066f610107ca1efa485e1e
