### ISSUE TITLE
View All Grant Elections

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#27]
1. As a user, when I visit the Grant Elections page, I can see a list of Grant Elections with the following information:
Grant Name (e.g. Yearly Grant - Jan. 26 2021 - Jan. 26, 2022)
Status: Open or Closed

2. Filtering: As a user, when I am on the Grant Elections page, I will see an option to filter the Grant Elections by: All, Active, Closed

Given when I click on a live Grant Election, I will be redirected to the “View Single Grant Election Page” page

Given when I click on a closed Grant Election, I will be redirected to the “View Single Grant Election Page” page

**Comment by anthonymartin** [comment]
1. As a user, when I visit the Grant Elections page, I can see a list of Grant Elections with the following information:
Grant Name (e.g. Yearly Grant - Jan. 26 2021 - Jan. 26, 2022)
Status: Open or Closed

2. Filtering: As a user, when I am on the Grant Elections page, I will see an option to filter the Grant Elections by: All, Active, Closed

Given when I click on a live Grant Election, I will be redirected to the “View Single Grant Election Page” page

Given when I click on a closed Grant Election, I will be redirected to the “View Single Grant Election Page” page

**Comment by Amiroxoxo** [comment]
This is complete right?
