### ISSUE TITLE
Create dependency graph

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#274]
All core contracts should have their dependencies mapped in a graph

**Comment by ecmendenhall** [comment]
Here's a tool for VSCode that does this: https://github.com/ConsenSys/vscode-solidity-auditor

**Comment by RedVeil** [comment]
Workflow:
1. Pull Dependency Graph with solidity-auditor
2. Load .dot into miro or similar
3. Add additional contracts where solidity-auditor is too simplistic

**Comment by RedVeil** [comment]
If possible find tool to autogenerate the depedency graph entirely

**Comment by anthonymartin** [comment]
This tool would allow us to generate the dependency graphs that are used by vscode-solidity author : https://github.com/ConsenSys/surya

Now that our docgen for contracts is working (https://app.gitbook.com/@popcorn-dao/s/popcorndao/v/develop-docgen/) we should be able to do the following:

1. generate the dependency and inheritance graphs using surya for each contract that's output from the docgen tool
2. link to the images within the contract.hbs (which contains the markdown template for each contract)
3. ensure the final result is clean 

![Screen Shot 2021-09-15 at 11.54.00 AM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/89bb341a-bd17-46f1-938d-b6cfc45c8e31)![Screen Shot 2021-09-15 at 11.53.32 AM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/6cd15d86-d876-4906-9174-f421cf3aaa07)

**Comment by anthonymartin** [comment]
relates to #484
