### ISSUE TITLE
Handle min_amount/min_mint_amount in Curve interactions

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/workspace#279]
In most of our interactions with Curve, we have deferred setting the `min_mint_amount`/`min_amount` parameters when adding/removing liquidity, and instead set these to zero. 

We should instead set a sensible default and optionally expose this parameter to the end user. Curve shows this as the "max slippage" setting on their deposit interface here:

![Screen Shot 2021-07-21 at 9.37.31 AM.png](https://images.zenhubusercontent.com/60ac1832916bb9d70bfff9c3/ed1fad19-4485-4c8b-bf34-a8dd4fc2ed57)

Zap in/out, pool deposits/withdrawals, and tokenset mints/redeems probably all need to pass through this parameter.

**Comment by anthonymartin** [comment]
* update Zapper: ZapIn/ZapOut to accept slippage
* add tests to simulate slippage in zapper
* add slippage parameter to batch mint and batch redeem in token set batch contract
* Use mainnet fork tests

**Comment by RedVeil** [comment]
Is this still an open Ticket? I feel like we "solved" this with our slippage require in batchMint and batchRedeem
