### ISSUE TITLE
Replace OpenZeppelin Ownable with Owned

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/workspace#284]
`Pool` and `BeneficiaryRegistry` are using OpenZeppelin `Ownable`, while everything else uses Synthetix `Owned`. 

Should we use one or the other everywhere?

**Comment by ecmendenhall** [comment]
`Pool` and `BeneficiaryRegistry` are using OpenZeppelin `Ownable`, while everything else uses Synthetix `Owned`. 

Should we use one or the other everywhere?

**Comment by anthonymartin** [comment]
* All contracts which own another must implement an Owner contract which exposes an accept ownership function that accepts ownership of the owned contract
