### ISSUE TITLE
Implement Token List on Rewards Manager frontend

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#288]
In the rewards manager frontend, it should be possible to select a token to swap from https://tokenlists.org/token-list?url=tokens.1inch.eth

The UI should allow one to search for a token by name or symbol and display the results in a dropdown based on the input value.

**Comment by FanFanDAO** [comment]
@anthonymartin @RedVeil Do you have more info about this? Is this under SC?
