### ISSUE TITLE
View Single Grant Election Page

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#29]
As a user, when I am viewing a single Grant Election I will see:

- Grant Name (e.g. Yearly Grant - Jan. 26 2021 - Jan. 26, 2022)
- Description
- Fixed Term Indicator: Monthly, Quarterly, Yearly
- Status: Voting Open, Registration Open, Closed
- Beneficiary List with the following information:
    - Organization Name
    - Organization picture/image
    - Slider (for allocating votes)
    - number of Allocated votes

Given when I click on a Beneficiary from the Beneficiary List on the Grant Election page, I will be brought to the “View Single Beneficiary” page

**Comment by anthonymartin** [comment]
As a user, when I am viewing a single Grant Election I will see:

- Grant Name (e.g. Yearly Grant - Jan. 26 2021 - Jan. 26, 2022)
- Description
- Fixed Term Indicator: Monthly, Quarterly, Yearly
- Status: Voting Open, Registration Open, Closed
- Beneficiary List with the following information:
    - Organization Name
    - Organization picture/image
    - Slider (for allocating votes)
    - # of Allocated votes

Given when I click on a Beneficiary from the Beneficiary List on the Grant Election page, I will be brought to the “View Single Beneficiary” page

**Comment by Amiroxoxo** [comment]
I'll take this on.
