### ISSUE TITLE
Allow privileged addresses to propose and finalize grant election results

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#291]
The `GrantElections.proposeFinalization` and `GrantElections.finalizeElection` functions should allow only a privileged proposer and a privileged finalizer to propose and finalization elections respectively. 

_Originally posted by @anthonymartin in https://github.com/popcorndao/workspace/pull/198#discussion_r677615640_

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/434
