### ISSUE TITLE
Grant Election Voting

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#30]
A. As a user on the “View Single Grant Election Page”, if I have not connected my wallet, I will see a button asking me to connect my wallet. Given that my wallet is connected, I will be able to see a CTA to lock tokens to vote in the election.

B. As a user, given that I try to vote by adjusting a slider on Beneficiaries in a Grant Election which has not ended, if I have not locked POP, then will not be able to vote and I will see a prompt asking me to lock POP tokens for voting.

C. As a user, given that I try to vote on Beneficiaries in a Grant Election which has not ended, if I have locked POP, then I will see a slider next to each Beneficiary which I can slide to allocate my vote which will then submit a transaction to the blockchain.

D. As a user that is adjusting a slider to allocate my votes, I will see my voting credit balance decrease. The voting credit balance will be displayed and fixed to be always visible.

E. Given that I try to vote for a Beneficiary in a Grant Election which has not ended and I exhaust my votes, I can not allocate votes to any other Beneficiary.

F. Given that I try to vote on Beneficiaries in a Grant Election which has not ended and I allocate desired amounts to Beneficiaries, I need to click Vote to submit vote which will then submit a transaction to the blockchain.

G. Given I exhausted votes in a Grant Election(s), I will not be able to assign votes to Beneficiaries again.

**Comment by Amiroxoxo** [comment]
Whats CTA? is it a modal?

I assume locked pop is a state variable that is loaded when the page renders so I can just use a dummy variable for this.

**Comment by anthonymartin** [comment]
The call to action can be a simple notification/alert like this: https://tailwindui.com/components/application-ui/feedback/alerts

For retrieving voiceCredits you can use the `getVoiceCredits` from `Staking` class here: https://github.com/popcorndao/workspace/pull/47/files

**Comment by anthonymartin** [comment]
- To update deployWithValues with GrantElection fixtures for initialization and beneficiary registration
