### ISSUE TITLE
replace this with `Object.keys(ProposalStatus).map` for dynamic display

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#301]
In `packages/app/components/Proposals/ProposalGrid.tsx` replace `new Array(6).fill(undefined).map` with `Object.keys(ProposalStatus).map` for dynamic display of proposal statuses

_Originally posted by @anthonymartin in https://github.com/popcorndao/workspace/pull/201#r679240290_

![Screen Shot 2021-08-03 at 5.48.43 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/ca869b48-1f4a-41b6-b717-cff6ffdfd595)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/382
