### ISSUE TITLE
Update state after web3-interactions

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/workspace#313]
We should update the state after successful transactions to immedately display the change.
(without needing to refresh the page)

- Show new pop balance, staked pop and voice credits after interaction on the staking page 

- Show new votes after voting in grant elections/beneficiary proposals.

- Hide voting interface after voting on beneficiary proposal

- Show new balances after interacting with rewardsManager.

- update which vaults are claimable and how much pop are locked for beneficiary Vaults and voting incentives

**Comment by anthonymartin** [comment]
@RedVeil do you have more details to add to this ticket to make the success criteria clear?
