### ISSUE TITLE
Apply consistent heights of Beneficiary / Proposal Cards

### ISSUE THREAD

**Issue by mefuru** [popcorndao/workspace#324]
1. The amount of text shown in a card body varies, resulting in Cards of varying heights. Change so that we have consistent heights 

2. The truncate function removes the last words and adds '...' to a short description. If the description is < x num characters, show in its entirety. 

Example

![image](https://user-images.githubusercontent.com/3315297/128528708-a76d1728-a524-4e19-ac00-80d82cb9040d.png)

Acceptance criteria - all cards are of the same height and short descriptions are not prematurely cut off.

**Comment by anthonymartin** [comment]
@mefuru could you look at the conflicts in this branch? 
https://github.com/popcorndao/workspace/pull/379
