### ISSUE TITLE
Fix 'Total Votes' in Nomination/Takedown pages

### ISSUE THREAD

**Issue by mefuru** [popcorndao/workspace#326]
Currently, we get an NaN for total votes. Acceptance criteria is to show the addition of yays and nays and to display the total in the same format as them.

![image](https://user-images.githubusercontent.com/3315297/128539821-3183171e-3430-403b-9b11-c9e07207ff08.png)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/384
