### ISSUE TITLE
Keeper Stake

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/workspace#333]
Functions that require a a keeper to call it should also require the keeper to have staked some POP.

Changes KeeperIncentives

**Comment by anthonymartin** [comment]
* to update RewardsManager.swapTokenForRewards to enforce minimum time between swaps per token swap
* to add keeper incentives to GrantElections.initialize()
* to add (non-keeper) incentives to GrantElections.approveFinalization

**Comment by RedVeil** [comment]
Keeper Incentive now required staked POP

https://github.com/popcorndao/workspace/pull/405

**Comment by RedVeil** [comment]
Its updated and ready https://github.com/popcorndao/workspace/pull/405.

**Comment by RedVeil** [comment]
Its not possible to combine KeeperIncentives and ParticipationRewards in a good way with GrantElections.
Even without the UsesPOP issue they both rely on Governed which cant be instantiated twice. But it also cant be taken out of one of them. Therefore id propose currently that a new election is simply started by an NGO that wants grants or us. It doesnt cost too much gas and shouldnt be called that often so i think this could be fine.
