### ISSUE TITLE
Keeper Burn (simple)

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/workspace#334]
We want to add POP burn to keeperIncentives. This way every time a keeper calls an incentivized function, some POP would be burned.

- KeeperIncentive needs to be updated

**Comment by anthonymartin** [comment]
@ecmendenhall @mefuru @RedVeil @yaoandrew Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/334?planning-poker)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/422

**Comment by RedVeil** [comment]
Keeper functions now "burn" a portion of the incentives everytime a keeper calls an incentivized function.
We send the POP to the beaconChain staking address where they shouldnt be accessible anymore.

**Comment by anthonymartin** [comment]
@RedVeil tests are not passing in this branch - assigning back to you
