### ISSUE TITLE
Contract Registry

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/workspace#337]
Since the popcorn ecosystem contains more and more contracts its getting difficult to keep track of them. A lot of contracts need to interact with each other and have setter functions to set the correct address of a contract they need to interact with.
This could be simplified by one central contract registry. 
Instead of storing a specific address the caller-contract would call ContractRegistry for the address of the contract it wants to interact with.

This would change all contracts.

**Comment by anthonymartin** [comment]
@ecmendenhall @RedVeil @mefuru Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/337?planning-poker)
