### ISSUE TITLE
Show error when user supplies an ethereum address that does not point to a contract when adding a contract

### ISSUE THREAD

**Issue by mefuru** [popcorndao/workspace#349]
Scenario: As a user I provide an Ethereum address that does not point to a contract when adding a new contract
Given: I'm on the dashboard page
When: I click on add contract and enter a valid Ethereum address but the address does not point to a contract
Then: I will receive a pop up notification informing them that the 'Ethereum address: ADDRESS does not point to a contract'.

**Comment by ecmendenhall** [comment]
https://docs.ethers.io/v5/api/providers/provider/#Provider-getCode

**Comment by mefuru** [comment]
https://tailwindui.com/components/application-ui/feedback/alerts#component-bfa7bc8484740ff2b3dfabe5fd318b25
