### ISSUE TITLE
Display data for transaction vol and co2 release for each contract

### ISSUE THREAD

**Issue by mefuru** [popcorndao/workspace#354]
Feature: As a user, I will see emission data for each contract in two boxes adjacent to an emission chart
A user navigates to the dashboard. Given they scroll to a contract and when that contract data has loaded correctly, then they will see two boxes.

The first box will contain CO2 emission data. This includes the weight of emissions (g if < 1 kg, in kg if greater) and the % change in emissions over the period. If the emissions have decreased, this value will be in green. It'll be in red if the emissions have increased.

The second box will contain transaction data. This includes the number of transactions (in units if < 1k, in k if greater) and the % change in transaction vol over the period. Unsure if we should colour code this as CO2 emissions are more pertinent.

**Comment by RedVeil** [comment]
How do we know if the contract already gets co2 offsets? Cause if we dont wouldnt it always be red?

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/459

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/459
