### ISSUE TITLE
withdrawFromDepositQueue

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#358]
withdraws 3crv from deposit queue before the batch is processed

`withdrawFromDepositQueue(bytes32[] batchId, uint256 amountIn3CRV)`
* background:
  * A user may want to withdraw their deposited assets from the deposit queue before the deposit queue has been processed. The batch deposit/withdraw contract should implement a function to withdraw some amount from the deposit/withdraw queue in 3CRV. The when withdrawing from the deposit queue, the total issued shares and the shares for the specific deposit should be updated.
* specifications
  * When calling this function, the amount the tokens specified should be withdrawn from the deposit queue.

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/399
