### ISSUE TITLE
Navigation & Layout

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#39]
![Screen Shot 2021-03-18 at 4.58.22 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/b9b31557-a8a5-49d7-bcfc-25c142d1fa62)

A navigation bar should be created with the above elements.

**Comment by mefuru** [comment]
Consider having separate menu items for Beneficiaries and Beneficiary Proposals as below.

![image](https://user-images.githubusercontent.com/3315297/117980351-2d067000-b334-11eb-8046-c40244e1152a.png)

[source](https://whimsical.com/beneficiaries-FSyB6zL27EGt7JA7Fu9GPr)
