### ISSUE TITLE
add etherscan link to website

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#402]
On the bottom of the website we should add:

[Popcorn (POP) Token](https://etherscan.io/token/0xd0cd466b34a24fcb2f87676278af2005ca8a78c4)

**Comment by Stanley-Okwii** [comment]
@anthonymartin , Should this link be on this page: https://github.com/popcorndao/workspace/blob/b46bd594d8b972fec493492ddd210407cca97501/packages/app/pages/index.tsx#L1-L198?

**Comment by anthonymartin** [comment]
It should be on that index page in the `main` branch
