### ISSUE TITLE
Run fork tests in CI/CD

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#407]
affects branch: `develop`

**Background**
We are running tests automatically through github actions (see `.github/workflows/run-tests.yml`), but recently we've added another type of test (a fork test), which requires an RPC connection to fork a mainnet version of ethereum contracts for use within a distinct suite of tests. This RPC connection is defined as an environment variable `FORKING_RPC_URL`. The problem with executing this test within the existing setup is that the environment variable is a secret which can not be made public (otherwise it risks getting abused). We would like to setup a distinct workflow to run the network/fork tests which takes advantage of github's encrypted secrets for running tests.

**Acceptance Criteria**
* `.github/workflows/run-tests.yml` should be copied into `.github/workflows/run-fork-tests.yml` while removing all but one nodejs environment from the execution matrix
* the workflow should use a secret for `FORKING_RPC_URL` and set the environment variable before executing the fork tests (`yarn run test:fork`)
* the fork test suite should run without exception when branches are updated on github

**Comment by leetdev** [comment]
@anthonymartin I'm sorry to keep bugging you, but could you please provide an update as to the status of this issue? If there are any problems, then perhaps I can provide some assistance?

**Comment by anthonymartin** [comment]
Looks good! Thank you @leetdev !
