### ISSUE TITLE
[Landing Page] Font Weight

### ISSUE THREAD

**Issue by annisharafi** [popcorndao/workspace#416]
Add more font weight to title and button 
<img width="133" alt="Screen Shot 2021-08-30 at 20 44 53" src="https://user-images.githubusercontent.com/22950097/131352155-9e69aded-c5e1-4b0f-be0d-112b9e7e2532.png">
<img width="412" alt="Screen Shot 2021-08-30 at 20 00 46" src="https://user-images.githubusercontent.com/22950097/131352208-b0c63e7e-57a5-4cab-9983-43e08ab96908.png">

**Comment by mefuru** [comment]
I can't replicate font weight reduction on smaller devices

![image.png](https://images.zenhubusercontent.com/60a268faa1e4f1205fb84283/be966dc3-78f1-4749-abc6-7575847e59b8)

**Comment by mefuru** [comment]
Closing as I'm unable to replicate in Chrome, Brave by simulating smaller screens nor on a couple of smaller phone screens.

**Comment by annisharafi** [comment]
issue solve, it might be a problem with my chrome. I open with safari the font weight works well
