### ISSUE TITLE
[Landing Page] Header

### ISSUE THREAD

**Issue by annisharafi** [popcorndao/workspace#417]
**13" desktop view**
The title size decreased but it seems not going well with desc, maybe we also dec desc font 1.125 rem
<img width="366" alt="Screen Shot 2021-08-30 at 20 06 13" src="https://user-images.githubusercontent.com/22950097/131352478-f89a634f-1654-481a-bf6e-3d2a16bef05f.png">

**Comment by mefuru** [comment]
I can't replicate the decrease in font-weight or size.![image.png](https://images.zenhubusercontent.com/60a268faa1e4f1205fb84283/cb563f98-21ad-4365-bbac-d84e3733abf1)

**Comment by mefuru** [comment]
Closing as unable to replicate in Chrome nor Brave nor with http://responsivetesttool.com/

**Comment by annisharafi** [comment]
issue solved, check in safari
