### ISSUE TITLE
[Landing Page] Navigation 

### ISSUE THREAD

**Issue by annisharafi** [popcorndao/workspace#418]
**Mobile view**
Space between navigation and header too big than active burger button menu have

<img width="332" alt="Screen Shot 2021-08-30 at 20 21 55" src="https://user-images.githubusercontent.com/22950097/131352578-a6941712-b8f8-4879-a955-f11683b17f5a.png">
<img width="331" alt="Screen Shot 2021-08-30 at 20 22 29" src="https://user-images.githubusercontent.com/22950097/131352587-ff39147a-f306-443b-8224-6f6398be8947.png">

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/478
