### ISSUE TITLE
[Landing Page] How it works section

### ISSUE THREAD

**Issue by annisharafi** [popcorndao/workspace#419]
**All View**
1. more weight to title
2. reduce title card size into 1.875 rem
3. reduce space between title and desc into 1 rem

<img width="879" alt="Screen Shot 2021-08-30 at 20 25 00" src="https://user-images.githubusercontent.com/22950097/131352899-186e021c-9d1c-4185-b2d3-e72071bf031a.png">

**Ipad and below view**
1. card not centered because there is space right on card
<img width="376" alt="Screen Shot 2021-08-30 at 20 28 53" src="https://user-images.githubusercontent.com/22950097/131353085-37d63840-ee2c-4a35-b339-ec7e84bd1937.png">

**Comment by mefuru** [comment]
See PR https://github.com/popcorndao/workspace/pull/480
