### ISSUE TITLE
[Landing Page] Create Real World Impact Section

### ISSUE THREAD

**Issue by annisharafi** [popcorndao/workspace#420]
**22" Desktop below view**
1. image pushed to left and cropped
2. reduce image size and text width same as other have

<img width="1150" alt="Screen Shot 2021-08-30 at 20 32 49" src="https://user-images.githubusercontent.com/22950097/131353333-f4a128a8-bd6f-4af6-af42-087ef7b6e265.png">

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/481
