### ISSUE TITLE
[Landing Page] Footer

### ISSUE THREAD

**Issue by annisharafi** [popcorndao/workspace#421]
**Desktop and mobile view**

1. sometimes there is a thin line that might appear, but I don't really know the specific condition it appears
2. in screenshot mobile, it appears under countdown
3. on desktop appear above navigation above footer

<img width="365" alt="Screen Shot 2021-08-30 at 20 38 25" src="https://user-images.githubusercontent.com/22950097/131353676-f59c1ae1-4048-4438-92e7-2a838e94ea6d.png">

<img width="1182" alt="Screen Shot 2021-08-30 at 20 37 54" src="https://user-images.githubusercontent.com/22950097/131353662-44ec75ac-2eab-439b-aa21-56b44a200039.png">

**Comment by mefuru** [comment]
Interestingly, I am able to replicate in Chrome/Brave dev tools when setting the simulator to iPhone 6/7/8 Plus or iPhone X but only if the the simulator is zoomed in or out. But the thin line disappears when I set zoom to 100%. I'm also unable to replicate on iPad (10" display) nor 5.4" Android mobile.

Device: Mac
OS: MacOS
OS version: 11.2.3
Browser: Chrome/Brave
Browser version: 93.0.4577.63 (Official Build) (x86_64) / 1.29.76

![image](https://user-images.githubusercontent.com/3315297/133081280-4b2eb7ac-cdb1-4f48-b85c-16e33b9c8947.png)
![image](https://user-images.githubusercontent.com/3315297/133081312-b3ac8d5e-e10c-4c72-8611-bc20c3651b27.png)

**Comment by annisharafi** [comment]
Issue solved 

**check on** 
Device : macos
OS : big sur v 11.5.2
Browser : 
1. chrome Version 93.0.4577.63 (Official Build) (x86_64)
2. safari
