### ISSUE TITLE
HYSI deposit/withdraw interface

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#423]
The objective of this issue is to create a page in storybook with the different components found in this design:

![Screen Shot 2021-08-30 at 4.57.49 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/36c43fa7-140a-43ff-9023-2ecadcc759d2)

Including: connected wallet balance
deposit/withdraw interface
alert (3 kinds)
success/error states for form inputs

![Screen Shot 2021-08-30 at 5.00.30 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/7c347130-ce93-4dd0-a9fd-ae25c3b6401d)

**Comment by RedVeil** [comment]
The adapter currently provides the price for HYSI and 3CRV, Batches and Redeem/Mint Cooldowns.
The Frontend displays all necessary informations besides the cooldown.

TODO: 
1. The frontend has to be made into components
2. There needs to be state change for deposit and withdrawl
3. The cooldowns need to be displayed
4. The actual interaction for deposits and claiming need to be added

**Comment by RedVeil** [comment]
https://github.com/popcorndao/workspace/pull/487
