### ISSUE TITLE
mongo import of eth transactions

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#424]
1. Use etherscan API to grab transactions including gasUsed / gasPrice / timestamp from 01.01.2021 to date
* targeting 5 contracts:
POP: https://etherscan.io/token/0xd0cd466b34a24fcb2f87676278af2005ca8a78c4
yvCurve-USDN-0x3b96d491f067912d18563d56858ba7d6ec67a6fa
yvCurve-DUSD-0x30fcf7c6cdfc46ec237783d94fc78553e79d4e9c
yvCurve-FRAX-0xb4ada607b9d6b2c9ee07a275e9616b84ac560139
yvCurve-UST-0x1c6a9783f812b3af3abbf7de64c3cd7cc7d1af44

2. Import all transactions for the above into a mongodb

3. create api data access layer for mongodb to be used by the frontend (netlify function)

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/459
