### ISSUE TITLE
Update recharts y-axis domains

### ISSUE THREAD

**Issue by mefuru** [popcorndao/workspace#437]
Currently, the domain of co2 emissions and num transactions vary greatly and the AreaBarChart isn't readable:

![image](https://user-images.githubusercontent.com/3315297/131699608-787c1129-2a2f-47ba-be3a-19a161a04066.png)

I manually set the domain of each axis to map between 0 and the max for that dataKey to no avail:
```
 const dataMaxCO2Emissions = data.reduce(function (prev, current) {
    return prev.co2Emissions > current.co2Emissions ? prev : current;
  }).co2Emissions;
  const dataMaxNumTransactions = data.reduce(function (prev, current) {
    return prev.numTransactions > current.numTransactions ? prev : current;
  }).numTransactions;
  return (
    <div className="w-screen grid justify-items-stretch">
      <ResponsiveContainer
        className="justify-self-start ml-3"
        width="87%"
        height={height}
      >
        <ComposedChart data={data}>
          <XAxis dataKey="date" scale="band" hide={true}></XAxis>
          <YAxis
            yAxisId="right"
            orientation="right"
            dataKey="co2Emissions"
            tick={false}
            hide={true}
            domain={[0, dataMaxCO2Emissions]}
          />
          <YAxis
            yAxisId="left"
            orientation="left"
            dataKey="numTransactions"
            tick={false}
            hide={true}
            domain={[0, dataMaxNumTransactions]}
          />
```

The dummy data in storybook uses the same domain for both axis so we'll need to change this, too.

Acceptance criteria:
1. Update the randomised dummy data in `dummyEmissionsData.js` to reflect a higher variance for co2 emissions
2. Update storybook component so that data for axis are readable:

![image](https://user-images.githubusercontent.com/3315297/131701757-94073038-6958-4a79-99b2-3d104d185d99.png)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/437?planning-poker) with ZenHub @ecmendenhall @mefuru @Stanley-Okwii
