### ISSUE TITLE
Adaptive weight units

### ISSUE THREAD

**Issue by mefuru** [popcorndao/workspace#458]
CO2 emissions vary greatly by contract and date range.

Emissions for higher volume contracts across a multi month date range may result in emissions best denoted in kgs. Emissions for low volume contracts may result in emissions best denoted in µg.

Currently, we denote emissions in a constant weight unit.

Acceptance criteria - adapt emissions such that the absolute value is denoted in the most adequate multiple. This should be reflected in the charts, stat boxes for each contract and totals.

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/458?planning-poker) with ZenHub @mefuru @Stanley-Okwii

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/495
