### ISSUE TITLE
Add RPC for the frontend

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/workspace#496]
Add RPC for the frontend to display all onchain informations that dont need account specific data.

Currently all these infos (grant elections, hysi-price, staking apy ....) can only be displayed once a user connects with metamask. Therefore we should use an RPC to display all of these informations and only make connecting with their own wallet mandatory for onchain interactions.

affects: `sweet-caramel`

There should be a default RPC connection to use for the following chains:
Rinkeby
Mainnet
Polygon
Mumbai
Arbitrum
Rinkarby

* It is perhaps best to use an infura project key and dynamic URLs so that it would not be necessary to create an individual environment variable for each network.

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/496?planning-poker) with ZenHub @ecmendenhall @mefuru @RedVeil

**Comment by anthonymartin** [comment]
Consider using eagerConnect() from web3react example

**Comment by RedVeil** [comment]
same PR as network-switcher: https://github.com/popcorndao/sweet-caramel/pull/33
