### ISSUE TITLE
HYSI: layout and UI components

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#556]

**Comment by anthonymartin** [comment]
branch: `develop`

![Screen Shot 2021-10-04 at 1.34.55 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/0c2ed6ca-4351-4a82-98b9-755b2668c5e3)

![Screen Shot 2021-10-04 at 1.57.23 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/cd1e34e0-18c2-481f-8a90-c411a1c26221)

![Screen Shot 2021-10-04 at 1.59.05 PM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/e694b0c4-3807-469d-aeff-8142c7ba1596)

Background: We would like to convert the following UI into react components in storybook. The final deliverable should include all of the components and sub-components created and displayed all together on a page in storybook.

Acceptance Criteria:
* all hover states, implied and explicit should be created. This includes pointers for cursors on clickable elements, and hover states for interactive elements.
* Stat cards should be generic for reuse. This means that icons, titles and content would be passed as arguments to the component
* Clicking on deposit/withdraw will toggle between the two UIs for deposit and withdraw
* Claim table
* Countdown component will dynamically update the circle based on the amount of time that is left compared to the start time. When there is less than 12 hours left, the color should turn yellow.
*  A rechart chart should be used from the rechart library for the data visualization. This has already been implemented in the branch: `develop-emissions-db`
* the chart should update when selecting a time period for the graph
* the layout should adapt to a single column for mobile compatibility.
* Alert component (green notification at top)
* error states for form elements should be enabled as shown in the screenshot
* deposit/withdraw interface

The figma can be provided the above design

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/556?planning-poker) with ZenHub @ecmendenhall @RedVeil

**Comment by RedVeil** [comment]
Deposit/Withdraw interface, claiming table and countdown component are done https://github.com/popcorndao/workspace/pull/487
