### ISSUE TITLE
after deposit share message [placeholder]

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#600]
<img width="1231" alt="Screen Shot 2021-10-19 at 11 02 53 PM" src="https://user-images.githubusercontent.com/949506/137990350-12bc1df4-7697-47c9-9662-dcafe6a54994.png">

exact specs TBD

**Comment by FanFanDAO** [comment]
@anthonymartin We can have a pop up design :)

**Comment by FanFanDAO** [comment]
@annisharafi maybe we can use this similar image? Let's not say 100%
![Screen Shot 2022-01-06 at 5.08.59 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/74086817-cf07-47d1-9dce-bb417377560e)

**Comment by annisharafi** [comment]
sure, here it is
<img width="433" alt="Screen Shot 2022-01-07 at 00 34 22" src="https://user-images.githubusercontent.com/22950097/148425640-78999cbb-bac0-424e-b83c-eeff54acb16c.png">

**Comment by FanFanDAO** [comment]
@anthonymartin Let us know if it is all good. :)
![Screen Shot 2022-01-07 at 1.55.35 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c91f066a-f3e6-4693-aa26-726892d96eec)
