### ISSUE TITLE
Airdrop Contract

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#620]
**Smart Contract specifications**
* contract will use a Merkle root hash to verify claims
* contract should allow an owner to add a merkle root to a list of merkle roots for claims so that new distributions may be possible in the future using the same contract
* contract should expose a claim function to allow a user to claim tokens against a Merkle root addressable either by index or by the merkle root itself.
* After an address has made a claim against a merkle root, the user should not be able to make a subsequent claim against that root hash
* When a claim is made, the tokens will be transferred with vesting. In order to support this use-case the TokenManager interface should be used (see below). The token should be made transferrable only after 1 month. Additionally, the contract itself will not hold any tokens, only the TokenManager will hold the tokens.

```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.8.0;

interface ITokenManager {
  function assignVested(
    address _receiver,
    uint256 _amount,
    uint64 _start,
    uint64 _cliff,
    uint64 _vested,
    bool _revokable
  ) external returns (uint256);

}
```

**Comment by ecmendenhall** [comment]
We've decided to use xPOP + the Balancer Merkle Orchard rather than deploying our own contract here. Closing the PR for this—let's roll the rest of this work into #622.
