### ISSUE TITLE
Airdrop UI

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#621]
UI Specifications
1. The UI will use a JSON document to determine addresses that are eligible for an airdrop. When a user connects their wallet, the claims page will check if the connected address has a claim and will then display all available claims in a card.
2. As a user with a claimable airdrop, I will see a card with the number of tokens that are claimable. The card will also have a claim button.
3. As a user with a claimable airdrop, when I click the claim button on the card for a claimable drop, the airdrop contract's claim() function will be called with the distribution hash and proof which is retrieved from the JSON file. After the transaction is accepted I will see a confirmation and congratulations on the new POP. Additionally there will be a reminder that tokens are not transferrable for a period of one month after the claim is made.
4. The airdrop page should mention to users who have claimable POP that when they claim tokens, they will not be transferrable for a period of 1 month.

**Comment by anthonymartin** [comment]
screens are broken for me

![Screen Shot 2021-11-07 at 1.51.48 AM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/82abf5d0-7c61-4ed0-a011-8b4488309be0)

![Screen Shot 2021-11-07 at 1.51.33 AM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/bf25a1eb-85fb-43f5-8c92-3bd24c65df6a)

**Comment by RedVeil** [comment]
PR: https://github.com/popcorndao/airdrop-claim/commit/713d60edb0cd10949aaa11048d184c66416b9749
Currently working with only one airdrop at a time

**Comment by Amiroxoxo** [comment]
How can I test this? I'm not a verified claimer on the rinkeby contract.
