### ISSUE TITLE
Bridge ERC20 to arbitrum from mainnet

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#629]
*Background*

We would like to be able to transfer the POP erc20 from mainnet to arbitrum with high priority for the LBP. The arbitrum bridge is permissionless, so we would need to look into how exactly to bridge the token. It may require deploying a smart contract so some research needs to be done. 

POP mainnet address: 0xd0cd466b34a24fcb2f87676278af2005ca8a78c4

see process here:
https://github.com/OffchainLabs/arbitrum/tree/master/packages/arb-ts#bridge-a-standard-token

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/629?planning-poker) with ZenHub @ecmendenhall @mefuru @RedVeil

**Comment by anthonymartin** [comment]
done! https://arbiscan.io/token/0x68ead55c258d6fa5e46d67fc90f53211eab885be

**Comment by ecmendenhall** [comment]
:sparkles:
