### ISSUE TITLE
Research: convex locked staking, gasless voting and delegation

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#631]
## Background

[Convex Finance](https://convexfinance.com) has recently implemented locked staking, gasless voting and vote delegation for their token. This model is very mainnet friendly and amplifies the voice of any given stakers. The model could work very well for our purposes, so research should be done to understand the mechanics of their system.

## Acceptance criteria

1. All contracts and deployed addresses used for the model described should be collected, with notes on implementation. Creating a page on notion would be ideal. Here are some examples of pages and references: [references](https://www.notion.so/popcorn-network/References-19ca7734a77d4be6bf04a89244a68fc3) & [abbreviated table with key functions and deployed addresses](https://www.notion.so/popcorn-network/7162fa0feb9b4214b7b2f5fbe2612994?v=181e0f78e54a43388d05b2681e2c0cc3)  
2. A diagram should be created to outline the architecture used by Convex as it relates to locked staking with delegation and snapshot voting.
3. A written summary of the architecture should be provided

**Comment by ecmendenhall** [comment]
CVX contracts repo here: https://github.com/convex-eth/platform
