### ISSUE TITLE
Refactor docgen.js to specify solc version at file level

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#632]
## Background

The documentation generator requires that solidity files requiring certain versions are grouped in directories together. However, this requirement undermines the organization of the directory structure. Therefore we would like for the documentation generator to read the version from the solidity files directly so that solidity files can be grouped with other files with a different pragma defined.

https://github.com/popcorndao/workspace/pull/624

**Comment by anthonymartin** [comment]
this is ready for review here: https://github.com/popcorndao/workspace/pull/624

To test it, a new branch should be created with [this one as the base](https://github.com/popcorndao/workspace/pull/617) merging [#614]( https://github.com/popcorndao/workspace/pull/624) and the directory structure should be reverted back to the well-organized one, so that 617 can be merged into develop

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/632?planning-poker) with ZenHub @ecmendenhall @mefuru @RedVeil

**Comment by Amiroxoxo** [comment]
@anthonymartin did you make a typo?

should it be "... with this one as base merging #624" instead of #614

**Comment by Amiroxoxo** [comment]
How far back do I need to go to find the well organized older folder structure?

**Comment by Amiroxoxo** [comment]
@RedVeil I've done the file restructuring here as per the steps above.

One issue - the deployWithValues.js file is not up to date as it's trying to deploy the KeeperIncentives contract with just one argument instead of 3 (the two missing arguments are burnRate and requiredKeeperStake)

**Comment by Amiroxoxo** [comment]
PR: https://github.com/popcorndao/workspace/pull/659

**Comment by Amiroxoxo** [comment]
PR: https://github.com/popcorndao/workspace/pull/720

3/4 tests passed on my fork - the only failing one is Solidity Fork Tests but this seems to fail on any forked repo.
