### ISSUE TITLE
Team & Contributors page

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#638]

**Comment by FanFanDAO** [comment]
## Source File: 
https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2696%3A38057

## Deliverable:
1 x Team and Contributors Page

## Design Key Requirement:
- Bring brand and visual consistency that is reflected on the main site landing page

## Development Key Requirement:
- Full adaptive with a fluid transition between screen sizes. Adaptive meaning device tailored to mobiles, tablets, and desktops
- Use SVG and not PNG for all art
- Spacing and font sizes should match design
