### ISSUE TITLE
Sweet Caramel - Landing Page

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#642]
## Source File
- Frame name: Butter/Landing Page (New)
https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2585%3A22525

## Key Development Requirements
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Reference
![Screen Shot 2021-11-15 at 1.31.02 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8f47feff-f5bf-4403-a28e-e8d589ccb6c3)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/642?planning-poker) with ZenHub @Amiroxoxo @ecmendenhall @mefuru @RedVeil

**Comment by mefuru** [comment]
https://github.com/popcorndao/sweet-caramel/pull/26

Updated the copy a little, open to suggestions.

Looks pretty good on devices > 630px. We aren't targeting phone, right?

**Comment by FanFanDAO** [comment]
We will in the eventuality but for now the Butter and Sweet Caramel are
both desktop only.

**Comment by mefuru** [comment]
https://github.com/popcorndao/sweet-caramel/pull/26
