### ISSUE TITLE
 Frontend - Team & Contributors page

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#647]
## Source File
- Frame name: Main Site/Team & Contributors
https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2696%3A38057

## Deliverable
- 1 x Adaptive desktop site
- 1 x Adaptive Mobile site
- 1 x Adaptive Mobile Expandable Menu

## Key Development Requirements
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Reference:
![Screen Shot 2021-11-08 at 7.02.51 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/28befbe3-ff62-4840-9d6f-1f047b4e6f70)
![Screen Shot 2021-11-08 at 11.10.15 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/bb616f47-23ba-4949-bda2-f18d29e35f10)
![Screen Shot 2021-11-08 at 11.09.06 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/969142cc-6a65-4fc9-9ebb-b6cc18fce9ed)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/647?planning-poker) with ZenHub @ecmendenhall @mefuru @RedVeil

**Comment by FanFanDAO** [comment]
**Need update:** (The correct logo has a white center piece.)
## Source file
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=241%3A2

![Screen Shot 2021-11-16 at 10.51.47 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5296b478-9748-4e36-8fce-5b010fe75a39)
@mefuru

**Comment by FanFanDAO** [comment]
Need update: (Please update all GitHub contributors with the below images. Each image name corresponds to the contributor's name.)
## Source File
https://drive.google.com/drive/folders/1DhGcfrCeLE-b_g8DO-nXx70Gi4woaowR?usp=sharing

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/664/

**Comment by FanFanDAO** [comment]
## Update needed for Popstars under the contributors section:
File: https://docs.google.com/spreadsheets/d/1FlXsg6tElDNq9EYKf2ogvM4pG6oY6cz2SJuLi9Aw7LY/edit?usp=sharing

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/722
