### ISSUE TITLE
Frontend - Move countdown to top

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#649]
## Deliverables
- 1 x Adaptive mobile adjustment
- 1 x Adaptive web adjustment

## Source File
- Frame name: Landing Page/Desktop/Final
https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=1312%3A24094

## Key Development Requirements
- The bottom larger countdown will still be there.
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Reference
![Screen Shot 2021-11-08 at 6.18.55 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c0b416cb-1052-4323-853b-aee894a17239)
![Screen Shot 2021-11-09 at 1.39.21 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/66045ec3-3686-4690-a5a0-7c5cde3ea659)

**Comment by Amiroxoxo** [comment]
PR: https://github.com/popcorndao/workspace/pull/655
preview site: https://deploy-preview-655--popcorndao.netlify.app/

**Comment by thenerdcat** [comment]
![image.png](https://images.zenhubusercontent.com/618e0a9f244ff57db62bf323/47cb5a83-1089-4970-823c-73df3afb0272) font-weight here is different than in the design. it should be 500, not 700

**Comment by thenerdcat** [comment]
![image.png](https://images.zenhubusercontent.com/618e0a9f244ff57db62bf323/5d239b60-1b29-4a2e-832e-8d5ae927c750) define font weight 500 for this line

**Comment by thenerdcat** [comment]
at certain resolutions the start doing good with DeFi text looks like this:
![image.png](https://images.zenhubusercontent.com/618e0a9f244ff57db62bf323/841faae2-8cc0-48f7-8a51-da180eda5fd8)

**Comment by FanFanDAO** [comment]
Hi Fernand,

Being adaptive has been an issue! I hope we can somehow solve this either
by exploring other options instead of Tailwind since to my understanding it
creates problems for adaptive implementations. If you have any suggestions,
it would be super helpful to know and discuss them together with the team.

Currently, depending on the browsers, our font does continue to display
wrongly. (e.g. Chrome vs Safari)

@Anthony D Martin ***@***.***>  I certainly think using
bounties might not be the longer-term solution.

Best regards,

Fan
