### ISSUE TITLE
Frontend - Network switcher

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#652]
## Source File
- Frame name: https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2670%3A23567

## Key Development Requirements
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Reference
![Screen Shot 2021-11-26 at 4.25.10 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a6a6eb4e-193a-4822-ae99-af7e611f613c)
![Screen Shot 2021-11-11 at 2.20.43 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3552d778-77f5-4122-8e22-f8bb35366d50)
![Screen Shot 2021-11-11 at 2.21.16 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b2f692d2-74d0-4672-96f5-39d936261bc9)
![Screen Shot 2021-11-11 at 2.21.38 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ea728913-b357-49f8-8287-5d36d5a38243)
![Screen Shot 2021-11-11 at 2.21.45 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/cdf849d1-2204-45f0-a030-ceae359ee9fb)

**Comment by anthonymartin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Popcorn-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/652?planning-poker) with ZenHub @ecmendenhall @mefuru @RedVeil @Amiroxoxo

**Comment by FanFanDAO** [comment]
## Update 15.11.2021
- We need a hover state and on-press state if it comes to mobile one day. Please refer to the design below. Color: Gray/100
![Screen-Shot-2021-11-15-at-5.00.56-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/7c479a8c-ac25-4b71-b26d-c80bd444a698)

**Comment by FanFanDAO** [comment]
Update: visual ( @bhanusanghi the frontend is handled by you. It was not assigned to anyone. Please confirm. xox)
![Screen Shot 2021-11-29 at 3.16.56 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/7382d53f-6d92-4da9-a25d-3b305465519a)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/33
