### ISSUE TITLE
Marketing need - Code plugin

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#661]
## Task
- Add code to "Join the waitlist" button, both top and bottom of the page
- LinkedIn Insight Tag: I would like to install an Insight Tag to monitor conversions of the ads we are running on LinkedIn. I will give you the code we need to place on the buttons. Code is this one: window.lintrk('track', { conversion_id: 5594906 });

## Person to inform
- Please contact Jacopo saying the code is in the button now once you are done. :)

## Reference
![Screen Shot 2021-11-10 at 5.24.17 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/eb38ffd4-604f-416c-b5e0-ca208a2e52f8)![Screen Shot 2021-11-10 at 5.24.21 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/23ee5db3-bd53-414c-8ee3-d656078aac81)

**Comment by Amiroxoxo** [comment]
@anthonymartin 

Any reason why LinkedIn pixel code has not been merged to develop/main atm? I'm thinking of re-using it and just changing the conversion ID for this use case

Heres the commit: https://github.com/popcorndao/workspace/commit/91adf7b2e6ca409c730ecc5f9970ab5760217f07

**Comment by Amiroxoxo** [comment]
@anthonymartin Yep, I'm thinking of turning the conversion ID into a prop and then rendering it on the page if they click on the button. Sound good?

**Comment by anthonymartin** [comment]
sure sounds good

**Comment by Amiroxoxo** [comment]
PR: https://github.com/popcorndao/workspace/pull/662

Need to check it works properly with Jacopo
