### ISSUE TITLE
Setup snapshot to collect votes from multiple chains

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#665]
## Background

Since the POP token is found on multiple chains it is necessary to be able to conduct snapshot votes across the different chains.

## Assignment

Research how to setup a snapshot strategy that uses token balances from across several EVM compatible chains including arbitrum, polygon and mainnet. 

## Deliverables

Report findings on enabling multi-chain voting for snapshot.

**Comment by ecmendenhall** [comment]
Multichain Snapshot strategy might be a starting point here: https://github.com/snapshot-labs/snapshot-strategies/tree/master/src/strategies/multichain
