### ISSUE TITLE
Slippage - Sweet Caramel

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#668]
## Working File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2520%3A24038

## Key Design Requirements
- Be consistent with our brand and design system 1.0 (https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2975%3A36261)
- Functionalities as discussed with Leon: menu, give them some defaults selections,
and then an input if they really want to tweak it.
- Create an icon to represent the slippage

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## General Image References
![Screen-Shot-2021-11-15-at-10.37.27-AM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5339914c-0b62-442f-9026-3a544578cc77)

**Comment by FanFanDAO** [comment]
## Design Update 
- Slippage
![Slippage added.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9307f6ae-d8ca-45c2-86a6-6f30cfd0e469)
![slippage popup.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a8f78e30-570d-49cc-b458-6b6bc527d80f)
- Claim popover
![Claim popup.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9038ed7a-1f33-401b-a4cd-18ae528f95e9)
![Claim popup expanded.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/16d19da9-a17b-405f-994d-f3bdbe701ee5)
@anthonymartin @RedVeil

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/25 same as in #610 and #613
