### ISSUE TITLE
Sweet Caramel - Popover for Claim

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#675]
## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2585%3A22525

## Key Design Requirements
- Align with the brand and our design system 1.0
- Always think about mobile and desktop adaptiveness and friendliness at all times.
- Update the claim-listed view!!

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Reference
![Screen-Shot-2021-11-15-at-10.25.52-AM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/97df94cc-e26c-40e3-878c-9a52319506f6)
![Screen-Shot-2021-11-15-at-1.43.30-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/55c0a281-eccb-448c-8114-b50936cde210)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/25 same as in #610 and #613
