### ISSUE TITLE
Blockchain4Good Alliance Kick-off Invitation

### ISSUE THREAD

**Issue by MrsBadgerface** [popcorndao/workspace#705]
**Objective:**
A JPG that can be shared online via Twitter, in Discord communities, and via Direct Messages, inviting people to a one-off kick-off meeting about a Blockchain4Good Alliance that Popcorn is going to steward.

**Key requirements:**
- Long as opposed to wide.
- Clear and easy to read. 
- Uncluttered but friendly, and recognisable as something produced by Popcorn by the kind of images included.

**Design spec:**
All text and Tweets to be included are in the Google doc.
Header text: It’s time for #Blockchain4Good projects to come together.
Tweets to be included in full. However, they should not be so big since they are not the emphasis of this JPG.
Layout is up to designer: please lay out in a way that makes it the most readable and keeps the emphasis on the header text and a fairly strong call to action (the last paragraph).
Size of the JPG is not important but should be larger rather than small so it's easily shareable but readable.
1 version to be created.
Nothing to be excluded.

**Delivered by:** Tuesday 5pm CET

https://docs.google.com/document/d/17ivveGC9QcXplSfgAeialaGiW9x_F5ZLRvIK1wfnKQY/edit?usp=sharing

**Comment by MrsBadgerface** [comment]
Note: delivered by: Tuesday 23rd November.

**Comment by FanFanDAO** [comment]
Design ready: ![Blockchain4Good_Invitation.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/779423eb-21aa-47eb-a068-3a727eedad1a)
