### ISSUE TITLE
As seen in and Investor sections (Mobile & Desktop) - Popcorn.network

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#710]
## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=3538%3A34351

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2021-11-23 at 5.58.57 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d7e1f3ad-7147-4469-bd2e-8c4639a693ab)
![Screen Shot 2021-11-23 at 5.59.15 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/d92a665c-cdff-45ef-9dc5-3771fa777099)

**Comment by mefuru** [comment]
https://github.com/popcorndao/workspace/pull/717
