### ISSUE TITLE
Terms and Network chooser Page - Token Launch Auction

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#712]
## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=3629%3A32268

## Key Development Requirements
- Clean, lean, and organized code practices
- The module height should be fixed for both mobile and desktop
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2021-11-22 at 10.38.03 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/6597e7bc-7bf8-4c75-8670-35b435162f5e)
![Screen Shot 2021-11-22 at 12.08.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9aebfec3-9ef3-4e3a-8a75-93a4d4041a67)

**Comment by RedVeil** [comment]
Commit: https://github.com/popcorndao/workspace/pull/645/commits/05ba13ae5c1a6520a0a615ae6633e57be661d89d

Its still missing the correct conditions and links to the launch sites

**Comment by FanFanDAO** [comment]
@anthonymartin I saw you are now on this. I will focus on other tickets then. Let me know if you need anything for this ticket in terms of browser check and all that.

**Comment by RedVeil** [comment]
PR: https://github.com/popcorndao/workspace/pull/645/commits/05ba13ae5c1a6520a0a615ae6633e57be661d89d
