### ISSUE TITLE
Landing without countdown & remove Token Launch on top nav - Popcorn.network (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#715]
## Source File
- Screen (Landing Page/Desktop/Without Countdown)
https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=3656%3A32431

## Key Development Requirements
- Clean, lean, and organized code practices
- Remove Token Launch on top nav
- The module height should be fixed for both mobile and desktop
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Reference Image
![Without Countdown.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/0ba64e21-c789-4cd1-9682-7d4ad43fd320)

**Comment by FanFanDAO** [comment]
@Amiroxoxo Make sure the top navigation reflects: Logo, Whitepaper, Team & Contributors, and Early Access. :) xox

**Comment by anthonymartin** [comment]
@Amiroxoxo can you link to the PR here?

**Comment by Amiroxoxo** [comment]
PR: https://github.com/popcorndao/workspace/pull/719
Preview: https://deploy-preview-719--popcorndao.netlify.app/
