### ISSUE TITLE
Community Survey

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/workspace#756]

**Comment by FanFanDAO** [comment]
Hi @split-infinity I would like to catch up on the survey since I haven't heard back.

**Comment by FanFanDAO** [comment]
@split-infinity @anthonymartin Please update us on the draft when you have it then. 
Post it here, please. We need to get it started.

**Comment by split-infinity** [comment]
@FanFanDAO @anthonymartin 

Here is a draft of the survey https://zfrmz.eu/EdjRksfhpPiBcv7Mn4gJ

Some of the followup questions relating to mobile phones and NGO donations are nested. Let me know any question  additions/tweaks or additional info we should add. 

Fan should have edit access on zforms

**Comment by split-infinity** [comment]
btw this other ticket has additional info and the reference questions https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/research/1
