### ISSUE TITLE
Add Icons to Token Selection in Butter

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/workspace#765]
Currently Token Selection for Minting and Redeeming and Butter only displays the name of a token. The same goes for the popover when withdrawing 3CRV.

We should Add Icons to these inputs.

**Comment by mefuru** [comment]
https://github.com/popcorndao/sweet-caramel/pull/79

**Comment by FanFanDAO** [comment]
The connect wallet button on the module doesn't work somehow and I couldn't get to see the coded dropdown with these icons added. Let me know :)
