### ISSUE TITLE
Implement animation - Expandable Menu

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#766]
## Source 
https://app.zenhub.com/workspaces/token-launch-auction-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/685

**Comment by mefuru** [comment]
Also update for popcorn foundation  - https://github.com/popcorndao/popcorn-foundation/issues/12

**Comment by mefuru** [comment]
Foundation site - https://github.com/popcorndao/popcorn-foundation/pull/23

**Comment by FanFanDAO** [comment]
@RedVeil @anthonymartin If this looks good. We can implement to other sites.
https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/778

**Comment by anthonymartin** [comment]
lgtm
