### ISSUE TITLE
Made our master design files into small subdivided docs

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#772]
## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=241%3A2

## Key Requirements
- Organized, layers named
- Each file should accompany by the latest Design System for quick references
- We need to make all files private and only viewable to people who have been invited. We need to disable all share links.
- Please share each files to core team members as mentioned previously on Discord.

## Files to be created

- BenGov (Beneficiary Governance)
- Sweet Caramel
- Mainsite (The Kettle)
- Popcorn Foundation
- Marketing Collateral & Microsites

**Comment by FanFanDAO** [comment]
@anthonymartin Implementation is set to take place after our official launch for SC.

**Comment by annisharafi** [comment]
@FanFanDAO I suggest to turn our file into figma team, its better to handle separated file and have centralized component. It cost $15/team member
https://www.figma.com/best-practices/getting-started-with-teams-in-figma-organization/#:~:text=In%20Figma%20Organization%20you%20can,file%20organization%20and%20user%20permissions.&text=A%20team%20can%20have%20its,levels%20of%20visibility%20within%20Figma.

**Comment by annisharafi** [comment]
1. BenGov :
https://www.figma.com/file/1HomTXpX4nJxmxIcf4RVWi/%5BPopcorn%5D-BenGov?node-id=2975%3A36261

2. Sweet Caramel :
https://www.figma.com/file/RKk0FBwbPnoZGpj3X9qHQ4/%5BPopcorn%5D-Sweet-Caramel?node-id=2%3A78516

3. Mainsite :
https://www.figma.com/file/dSgjiyK3ZgBREe3UKQMz9a/%5BPopcorn%5D-Mainsite?node-id=2%3A78516

4. Popcorn Foundation
https://www.figma.com/file/9LhE9KBwxMCr6Mpc0thQJs/%5BPopcorn%5D-Popcorn-Foundation?node-id=2%3A78516

5. Marketing Collateral & Microsite
https://www.figma.com/file/Ua0DuFDYfZihXfOijlrbhr/%5BPopcorn%5D-Marketing-Collateral-%26-Microsites?node-id=2%3A78516
