### ISSUE TITLE
Fixes - Make the logo on the mobile menu look consistent with popcorn.network (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#778]
## Fixes
Make sure logo sizing and position should be the same as our current popcorn.network

## Reference Image
![Screen-Shot-2022-02-25-at-3.06.48-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/72476fa1-8e5a-44a3-a4c0-8ef2e7da9bca)

## Source File (Let me know if you can't access this file)
- https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as the Figma design.
- This page and the entire UX flow should be adaptive with fluid transition across all mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

**Comment by FanFanDAO** [comment]
@anthonymartin @RedVeil @Amiroxoxo 
Anthony has approved the animation, and we should get them all updated on our current sites: Main site, Foundation, and TLA. Butter/SC is our priority, so only get to this task once you are done with all things Sweat Caramel.

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/857

**Comment by FanFanDAO** [comment]
@RedVeil Feedback:
![Screen Shot 2022-02-28 at 2.45.55 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b6dab678-00eb-42d6-8c71-2952962219df)
![Screen Shot 2022-02-28 at 2.46.03 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/387883b8-8e5e-4f4f-a7a8-69f838d9e46e)
![Screen Shot 2022-02-28 at 2.46.09 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9f9c60c0-d278-40dc-9771-aa3c5f5222fa)

**Comment by FanFanDAO** [comment]
@RedVeil Feedback:
![Screen Shot 2022-02-28 at 2.46.09 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/39a4b08c-9819-49d9-98df-ec34723ea5c7)

**Comment by RedVeil** [comment]
is addressed

**Comment by FanFanDAO** [comment]
@RedVeil The sandwich menu should not lock to the browser. It stays with the top nav.
![Screen-Shot-2022-03-01-at-2.51.07-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/816f9ffc-ae06-4177-b05e-93c7ea981639)

**Comment by RedVeil** [comment]
updated in here: https://github.com/popcorndao/workspace/pull/862
Please approve this PR if it looks ok

**Comment by FanFanDAO** [comment]
@anthonymartin Looks good to me. :)
