### ISSUE TITLE
Fix footer error on our main site!

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#784]
## Situation
Not sure why the footer has been changed since we didn't work on the main site recently. We need the footer to be styled just like our design.

## Image Reference of the error
![Screen Shot 2021-12-27 at 5.29.10 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/72b06aa1-026c-459f-af06-61caa6a7067f)

## Design Source File
https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=241%3A2

**Comment by anthonymartin** [comment]
duplicates #745
