### ISSUE TITLE
Withdrawing deposited tokens before batch

### ISSUE THREAD

**Issue by Amirjab21** [popcorndao/workspace#786]
url: /butter

Steps to reproduce:
When I deposit 3CRV and then try to withdraw, it gives me an option asking which token I'd like to receive when I withdraw. 

I choose USDC, it confirms and then sends me 3CRV back anyway.

Should it give me an option to withdraw different tokens if I've deposited 3CRV or should it just send me back whatever I deposited?

**Comment by anthonymartin** [comment]
this was a bug that has been fixed
