### ISSUE TITLE
Staking/id bugs

### ISSUE THREAD

**Issue by Amirjab21** [popcorndao/workspace#787]
browser: Brave
OS: Mac OSX
url: /staking/[id]
POP/USDC LP Staking

**1**
Faulty staking/allow button for POP/USDC LP staking.

If I stake try to stake 100, it allows me to stake.

If I try to stake 1000, it asks me to approve. I approve and confirm tx and then it doesn't update and will ask me to approve again if I try to stake 1000 POP/USDC LP.

**2**

Bug: When I refresh the page when I'm at the route staking/[id], it takes me back to the url /staking

Improvement: The refresh should keep you on the page you were already on.

**Comment by FanFanDAO** [comment]
Amazing. Please update the design team per text changes so our files reflect the same UX copies. @Amirjab21
