### ISSUE TITLE
remove POP.transfer from sending rewards to staking

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#792]
https://github.com/popcorndao/workspace/blob/38489d85e5f633d4836991b54ec52a5d9f1d4cb8/packages/contracts/contracts/core/utils/RewardsManager.sol#L156

since PopLocker transfers pop on notifyRewardAmount, the POP transfer can be removed  here

**Comment by anthonymartin** [comment]
It's a workspace issue actually

**Comment by bhanusanghi** [comment]
Is this change still required or did someone look into this already ?

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/sweet-caramel/pull/620
