### ISSUE TITLE
Bug Bounty Button

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/workspace#817]
Immunefi is looking for us to put a bug bounty button or link on our homepage

Reference provided:
![bug bounty.PNG](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/5ff3204f-997d-4cac-9aa6-5a61988021f3)

Immunefi comarketing guide: https://drive.google.com/file/d/14VLdMplDawTgc_NM8Fw7Yo4dQ5R8T4ex/view?usp=sharing

Immunefi branding materials: https://drive.google.com/drive/u/0/folders/1Q13zrEOIi3feXwjI5X7w_7npv70dOypX

**Comment by FanFanDAO** [comment]
@RedVeil Let's discuss this.

**Comment by RedVeil** [comment]
im fine with this but we could also just put it in the footer.

**Comment by FanFanDAO** [comment]
@RedVeil @anthonymartin @split-infinity 
I have given two design options here. Let me know. :)
![Screen-Shot-2022-02-04-at-3.04.00-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3a26b24f-7d6e-4212-8bc5-6b5d9bd1b201)
![Screen-Shot-2022-02-04-at-3.01.48-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/72a0bd66-c647-43d4-a5d3-e5bae68e706a)

**Comment by anthonymartin** [comment]
Let's go with the first plain text version
