### ISSUE TITLE
Implement EIP-4626 for vault wrappers

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/workspace#820]
See the EIP-4626 spec here for all details: https://ethereum-magicians.org/t/eip-4626-yield-bearing-vault-standard/7900

Changes to our existing vault:

- Collapse `deposit` and `depositFor` into a single `deposit` function
- Add a `mint` function 
- Update `withdraw` to use underlying token value, rename current `withdraw` to `redeem`
- Add public `underlying` view that returns current `token` state variable
- Rename `totalValue` to `totalUnderlying`
- Implement `balanceOfUnderlying`
- Rename `valueFor` to `previewRedeem`
- Rename `pricePerPoolToken` to `exchangeRate`
- Implement previews: `_sharesForValue` becomes `previewDeposit`, implement `previewMint` and `previewWithdraw`
- Add separate `from` and `to` in `Deposit`/`Withdraw` events

**Comment by anthonymartin** [comment]
duplicated by #362 in sweet-caramel repo
