### ISSUE TITLE
Adding new logos to Partnership section on our homepage

### ISSUE THREAD

**Issue by MrsBadgerface** [popcorndao/workspace#823]
**Scope:** Add partnership logos to the partnership section on our home page:

![Screenshot 2022-02-08 at 10.34.48.png](https://images.zenhubusercontent.com/6080275bb891652bba91375c/8d4fb05d-4606-480f-86cf-e46fc94cab1d)

(In no particular order)

**1. BanklessDAO**

![BanklessDOALogo_ForOnLight_512X512 (1).png](https://images.zenhubusercontent.com/6080275bb891652bba91375c/ae72d2d5-e646-4e00-83c3-739def0f9447)

**2. Olympus Give (if it's possible to make it grey, since the only logo created for Give is in white)**

![OlympusGive_Logo (white).png](https://images.zenhubusercontent.com/6080275bb891652bba91375c/37729ea4-bb40-41f3-bc42-b124c3315fd5)

![OlympusGive_Logo (white).svg](https://images.zenhubusercontent.com/6080275bb891652bba91375c/189dbdd0-815e-47ed-baf7-54a876dc75e2)

**3. Giveth**

![Giveth - blue logo.png](https://images.zenhubusercontent.com/6080275bb891652bba91375c/7ea54d3c-22c2-402d-b2bf-d567542ac97b)

**Timescales:** No urgency

**Comment by FanFanDAO** [comment]
@anthonymartin Design done. A new ticket will be created for the frontend. 
![Screen Shot 2022-02-21 at 11.39.48 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/22097de1-600e-4e0b-ad35-8e07945f056e)
