### ISSUE TITLE
Update website's team and contributor page so it's current

### ISSUE THREAD

**Issue by MrsBadgerface** [popcorndao/workspace#824]
**Scope:** To update the https://popcorn.network/team page so it's current.

**Specifics:**

1. Please remove Melody Song and Oscar Jacobsen.

2. Please add the following:

Justin Condren
https://twitter.com/condrenjustin
https://www.linkedin.com/in/justincondren/

Lili Vidal
https://twitter.com/lili_vdal
(No linkedin page)

Arne Zerndt
https://twitter.com/ArneZerndt
https://www.linkedin.com/in/arne-zerndt/

**Timescale:** Not urgent

**Comment by FanFanDAO** [comment]
@annisharafi These above folks would require illustrations drawn. Meanwhile, use the placeholder images we had previously created. The placeholder illustrations should be randomized so no two of the same next to each other.
