### ISSUE TITLE
Add Immunefi on the footer of popcorn.network

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#827]
## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=241%3A2

## Key Development Requirements
- Clean, lean, and organized code practices
- The module height should be fixed for both mobile and desktop
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-09 at 5.31.31 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/25121c4a-9253-4c15-ba14-c45940405bd5)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/844
