### ISSUE TITLE
Footer on popcorn.network is not styled correctly

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#828]
## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=241%3A2

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
This is our current look on popcorn.network
![screencapture-popcorn-network-2022-02-09-17_37_11.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/618c3322-38c7-4881-a9af-f2a821035364)
This is how the correct design looks like
![Screen Shot 2022-02-09 at 5.38.00 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/5e6efba9-aaec-49c4-9a69-ac75aedcd389)

**Comment by thenerdcat** [comment]
Footer style has been updated for both desktop and mobile. Check PR here: https://deploy-preview-865--popcorndao.netlify.app/

I have preserved all the data and styling for that data in the footer, and have only changed the background style. Let me know if there is any other change needed here.

**Comment by FanFanDAO** [comment]
@thenerdcat Feedback as observed on Chrome and Safari. 
![Screen-Shot-2022-03-08-at-5.00.13-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e9b8ba4a-aee8-488e-b113-c35a4a2ed293)
![Screen-Shot-2022-03-08-at-5.00.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/171fdfea-e1a8-4eff-b6a7-aa63495331d0)

Correct design
( Source: https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=2%3A40262)
![Screen Shot 2022-03-08 at 5.00.13 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/28b64534-f4c5-433b-b71d-380731defef3)

**Comment by thenerdcat** [comment]
Improvements done. I have worked on making it as similar as possible to the figma design on both desktop and mobile.
PR https://github.com/popcorndao/workspace/pull/865
Preview https://deploy-preview-865--popcorndao.netlify.app/

**Comment by FanFanDAO** [comment]
@thenerdcat let's change the below text to Demi. The designer made a mistake with classes. Other than that, it looks good to me. :)
![Screen Shot 2022-03-09 at 11.32.19 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ee8e22a1-88c4-4292-b182-05a5ae43d47c)
![Screen Shot 2022-03-09 at 11.32.22 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/117bc757-5b9d-4e59-a49b-af324415caf6)

**Comment by thenerdcat** [comment]
Awesome! Done with the fixes.
PR #865
Preview https://deploy-preview-865--popcorndao.netlify.app/

**Comment by FanFanDAO** [comment]
@thenerdcat Somehow now Chrome and Safari show up like this for me. If it was no problem for you please assign this ticket to Anthony. 
![Screen Shot 2022-03-09 at 4.24.11 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/29e044b1-4057-4c5e-896b-7eca045154dc)

**Comment by thenerdcat** [comment]
![image.png](https://images.zenhubusercontent.com/618e0a9f244ff57db62bf323/faf68000-0405-4cbd-926e-072576e3e839) yes, it's looking fine in my end
