### ISSUE TITLE
Create an "Open App" button on the top nav of popcorn.network 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#829]
## Reference
- https://www.olympusdao.finance/
- https://beefy.finance/

## Key Design Requirements
- On brand and aligned with our Design System 1.0
- UX and its entire flow should be catered to both mobile and desktop at all widths and sizes
- Make sure you are thinking hover state, on-press state, and inactive state at all times when applicable

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

**Comment by annisharafi** [comment]
design update here
https://www.figma.com/file/dSgjiyK3ZgBREe3UKQMz9a/%5BPopcorn%5D-Mainsite?node-id=203%3A8013

**Comment by FanFanDAO** [comment]
@anthonymartin @RedVeil Since the "Early Access" button on popcorn.network is no longer relevant to our current stage; we should move it. Also, we should repurpose the join waitlist email input and instead start collecting emails in preparation for a future newsletter or product announcement. What do you guys think? 
![Screen Shot 2022-02-16 at 2.51.31 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8da7c0ae-f64a-4454-8d84-07f12b0b9522)

**Comment by RedVeil** [comment]
I think thats a good idea and the design just makes sense.

**Comment by FanFanDAO** [comment]
@RedVeil Can you speak with Arne and come up with all naming conventions for the above-mentioned items.
