### ISSUE TITLE
Update Our Partners - Popcorn.network (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#845]
## Source File
- https://www.figma.com/file/dSgjiyK3ZgBREe3UKQMz9a/%5BPopcorn%5D-Mainsite?node-id=2%3A40262

## Partner Logos
![DAO.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/253825d4-d071-4232-8388-f858705111a0)
![Giveth.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/e09817e4-e5e4-41c6-81b9-514959f12910)![Olympus Give.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/4d3ea111-d97a-43e0-85f9-4d6f7d0ad439)

## Key Development Requirements
- Logos should be size to the same height as our current logos on popcorn.network
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as our Figma design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-21 at 11.39.48 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/02623a21-8b35-4a77-b1a9-f5f47523716d)

**Comment by thenerdcat** [comment]
Done. PR link https://github.com/popcorndao/workspace/pull/860
PR is not creating a preview but you can find the screenshots below.
![image.png](https://images.zenhubusercontent.com/618e0a9f244ff57db62bf323/67f29ba0-ee76-475a-b7f4-869eef930aff)
![image.png](https://images.zenhubusercontent.com/618e0a9f244ff57db62bf323/851a5f6c-0f63-4373-99da-e0405dd01225)

**Comment by FanFanDAO** [comment]
@thenerdcat @RedVeil Somehow Fernando experienced difficulty with getting the PR to show. Let me know as soon as possible on the PR would be awesome! xox

**Comment by FanFanDAO** [comment]
@anthonymartin Looks good to me. :)
