### ISSUE TITLE
Team and Contributor Update (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#848]
## To-do

1. Please remove Melody Song and Oscar Jacobsen.
2. Please add the following:

Justin Condren
https://twitter.com/condrenjustin
https://www.linkedin.com/in/justincondren/

Lili Vidal
https://twitter.com/lili_vdal
(No linkedin page)

Arne Zerndt
https://twitter.com/ArneZerndt
https://www.linkedin.com/in/arne-zerndt/

## Placeholder images are ready on Figma (Portraits of the three are waiting to be created.)
- https://www.figma.com/file/dSgjiyK3ZgBREe3UKQMz9a/%5BPopcorn%5D-Mainsite?node-id=201%3A37154

## Key Development Requirements
- Clean, lean, and organized code practices
- The module height should be fixed for both mobile and desktop
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Screen Shot 2022-02-22 at 2.51.34 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/dd0a6c17-2fb0-4c54-9b80-e2a3539461b9)

**Comment by thenerdcat** [comment]
Done. PR https://github.com/popcorndao/workspace/pull/861
No preview was created for this one in workspace. Do you know why is this happening @RedVeil ? 
Preview Screenshots here:
 ![image.png](https://images.zenhubusercontent.com/618e0a9f244ff57db62bf323/94f9da78-a278-4f22-abee-c897668fae7e)
![image.png](https://images.zenhubusercontent.com/618e0a9f244ff57db62bf323/0506face-3791-4c77-a7ea-199c6ee7003e)
