### ISSUE TITLE
New dates needed on 2 new marketing graphics

### ISSUE THREAD

**Issue by MrsBadgerface** [popcorndao/workspace#849]
**Scope:** Use the attached template to create graphics for sessions 2 and 3 of the 3 session process.

**Details:**  All information to stay the same except for the session number, dates, and times, which need to change to:
 
1. Second session Friday 4th March at 1.30pm UTC
2. Third session Friday 11th March at 1.30pm UTC

**Template:**
![Screen Shot 2022-02-24 at 11.33.46.png](https://images.zenhubusercontent.com/6080275bb891652bba91375c/0948852a-30c9-4e90-a703-b32912307710)

**Delivery:** By Tuesday 1st March please. Thank you!

**Comment by annisharafi** [comment]
![community call-2](https://user-images.githubusercontent.com/22950097/156024947-b5bbde09-7a9b-46cc-9a4f-c53c51ef1a04.png)

![community call-3](https://user-images.githubusercontent.com/22950097/156025182-f1050f37-d967-4666-b079-1d7dd48450db.png)

**Comment by MrsBadgerface** [comment]
Wonderful, thanks!
