### ISSUE TITLE
Fixes - Mobile expandable menu needs to be styled correctly (popcorn.network)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#856]
## Fixes
Please check the reference image.

## Source File (Let me know if you can't access this file)
- https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as the Figma design.
- This page and the entire UX flow should be adaptive with fluid transition across all mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Reference Image
1. Correct design
![Screen Shot 2022-02-25 at 3.17.09 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/b6548a3a-4251-4b60-b544-08acbc4dd536)

2. popcorn.network
![Screen-Shot-2022-02-25-at-3.06.55-PM.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/39e24896-de73-4f2d-8b45-cdb2ad0e39a4)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/857

**Comment by FanFanDAO** [comment]
@RedVeil Feedback:
![Screen Shot 2022-02-28 at 2.46.03 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8c3ef0f3-7417-4ad7-8ca4-210323d3c6f8)
![Screen Shot 2022-02-28 at 2.45.55 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/18f637f8-d3a4-4696-a578-a21a4b1e1a65)

**Comment by FanFanDAO** [comment]
@anthonymartin the PR for this ticket shows only the correct font on Safari, but it is still displayed in the wrong weight for Chrome. If you know what is wrong, it would be great to fix this. Otherwise, if we based on the version from Safari, it looks good to me. https://deploy-preview-857--popcorndao.netlify.app/
