### ISSUE TITLE
Sweet Caramel Mobile Loaders 

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#866]
## Source File
- TBA

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as our Figma design.
- This page and the entire UX flow should be adaptive with fluid transition across all mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
TBA

**Comment by anthonymartin** [comment]
@RedVeil is there a PR for this one?
