### ISSUE TITLE
add all new contracts to emissions dashboard

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#868]
In order to measure carbon emissions, we must add the following contracts on _ethereum_ to the emissions dashboard:

https://www.notion.so/popcorn-network/Deployed-Contracts-59c1401d42d345ec85429db19104c330

**Comment by ecmendenhall** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Default-603eb49d1a9a0b0011b49b36/issues/popcorndao/workspace/868?planning-poker) with ZenHub @Amirjab21 @anthonymartin @bhanusanghi @leomarlo @RedVeil @thenerdcat

**Comment by Amirjab21** [comment]
Is there a design for this? Do we just want all the Ethereum mainnet contracts to be displayed as a list similar to how it looks in Notion? @anthonymartin

**Comment by anthonymartin** [comment]
this is to update emissions-dashboard.popcorn.network - it's in an emissions-dashboard branch on workspace repo

**Comment by Amirjab21** [comment]
PR: https://github.com/popcorndao/workspace/pull/459
