### ISSUE TITLE
Staking Contract Modal on the Rewards Page (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#871]
## Source File
- https://www.figma.com/file/smADaRAg8Xsfz946oT06qQ/Sweet-Caramel?node-id=6750%3A28653

## Key Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Reference Image
![Screen Shot 2022-03-22 at 3.48.12 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/893021f0-f179-45b4-8ba7-26cdc61e4866)

**Comment by arne-z** [comment]
![Screenshot_20220707_153426.png](https://images.zenhubusercontent.com/5c6e9b98b3d46374d6a0d6b3/80b83f54-7dc3-47bf-b7c3-72f8fd2061e2)

https://github.com/popcorndao/sweet-caramel/pull/934

**Comment by FanFanDAO** [comment]
@RedVeil We need to downsize the header font for mobile here within the cards from text-2xl to text-xl demi.
![Screen Shot 2022-07-08 at 1.15.04 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2929ee45-2e3e-487a-8171-944b81bb0516)
