### ISSUE TITLE
Workshop Design - uncover strategy and product focus for 2nd half of the year

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#888]
## Description
We’ve been recently having conversations about Defi strategy and core areas of focus for the 2nd half of the year. Various people have their ideas and reflections and we have made the decision within dev and product to initiate a product thinking workshop.

## Specific Acceptance Criteria
- An interactive group workshop
- A flow that enables us to uncover and narrow down the problem space
- Medium: Miro board session
- Loom video recorded for easy referral

**Comment by arne-z** [comment]
Current Draft in this Miro Board:
https://miro.com/app/board/uXjVO0MvkLk=/

**Comment by arne-z** [comment]
@RedVeil we still need to finish the strategies step with additional info for the other strategies here.
