### ISSUE TITLE
Use decimals to automatically parse and convert Big Numbers from the start

### ISSUE THREAD

**Issue by Amirjab21** [popcorndao/workspace#892]
Instead of using parseEther and formatEther, we should always be using parseUnits(value, decimals) and formatUnits(value, decimals)

This will allow us to remove code that does conversions from different decimal tokens.

**Comment by RedVeil** [comment]
@Amirjab21 I finally left some comments. Could you merge dev in before working on those? :)

**Comment by RedVeil** [comment]
@anthonymartin i cleaned it up a little and it looks good to me. The hardhat tests that i did by clicking around seemed all fine. But since this is quite the large change i would like you to also check it.

**Comment by anthonymartin** [comment]
@RedVeil looks like more changes were made - please take a look
