### ISSUE TITLE
Add fees to VaultZapper

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/workspace#894]
Add a configurable fee to the VaultZapper on zap in and zap out.

- Fees should be configurable by an authorized role. See the vault fee structure for an example.
- Fees should be validated and limited to an amount less than 100%.
- The Zapper should accrue fees in the underlying vault asset, i.e. Curve LP tokens.
- An authorized role should be able to convert accrued fees to stablecoin and send them to another address. It's possible to do this by using the zapper itself.

**Comment by RedVeil** [comment]
- FeeLogic can be taken from Vault.sol

**Comment by anthonymartin** [comment]
I've added comments to this PR: https://github.com/popcorndao/sweet-caramel/pull/711#pullrequestreview-1027772061

**Comment by anthonymartin** [comment]
pushing this back to @RedVeil to fix failing tests
