### ISSUE TITLE
Create frontend module for 0x 

### ISSUE THREAD

**Issue by ecmendenhall** [popcorndao/workspace#895]
If a user wants to use the VaultZapper to zap out of vault shares into an asset that's not in the underlying Curve pool, they need to provide valid calldata to perform a swap using 0x. This calldata can be retrieved offchain from the 0x API. 

We'd like to create a module that will manage these calculations for use on the frontend. 

Parameters required to Zap in (see example [here](https://github.com/popcorndao/sweet-caramel/blob/db82e2e60cec2678c11970da0680457a5648c1c0/packages/hardhat/test/forge/fork/ZeroXZapper.t.sol#L92)):
- Buy token address
- Sell token address
- Sell amount 
- Slippage

Workflow: Pass parameters to the 0x API, parse response, return calldata.
Return: Calldata from the 0x API

Parameters required to Zap out (see example [here](https://github.com/popcorndao/sweet-caramel/blob/db82e2e60cec2678c11970da0680457a5648c1c0/packages/hardhat/test/forge/fork/ZeroXZapper.t.sol#L246):
- Buy token address
- Sell token address
- Sell amount, calculated from onchain view
- Slippage

Workflow: Call `previewZapOutTokenAmount` on zapper, pass parameters to the 0x API, parse response, return calldata.
Return: Calldata from the 0x API

**Comment by anthonymartin** [comment]
https://github.com/popcorndao/sweet-caramel/pull/850
