### ISSUE TITLE
Landing page 2022 - popcorn.network (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#902]
## Description
In the reference image below, you are looking at the brand new page for the popcorn.network site. 
Explainer Loom video: https://www.loom.com/share/a264dcae4b3846779152a183156f5066

## Specific Acceptance Criteria
- 12 column grids system (Please study the Figma file)
- use nextJS images (faster load)
- Fetch data for TVL and individual products
- Button hover state for Submit
- Button hover and click state for key CTA
- Loop auto-animated logos for Partners and As Seen In sections
- Layout of the page
- Submit email function should work as normal for the Newsletter sign up
- Scroll lock to screen element for the top protocol stats, header, copy, and newsletter sign up 
- Popcorn should be auto-selected upon landing on the page. The popcorn icon and the Popcorn text tab take the user to the landing (Home)

## Resources
(Please study the Figma file carefully.)
https://www.figma.com/file/4Di8ZA300BLop08MV46eWw/Mainsite?node-id=993%3A12283

## General Development Requirements
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-07-19 at 11.40.24 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/caabe789-32b7-4538-a9ff-377751fe3382)
![Screen Shot 2022-07-19 at 11.01.30 AM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f597f63c-c1c9-44b9-85fa-91985aebd2ce )
![Rebrand13072022.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/99dc8f4a-5c40-4d4a-abd0-fa1d553a07ea)
![Mobile menu.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/cfd38411-e22a-4c07-b514-a4ffb3821181)

**Comment by Ajiva-D** [comment]
pr: https://github.com/popcorndao/popcorn.network/pull/10

**Comment by RedVeil** [comment]
Could you check out the build issue?

**Comment by FanFanDAO** [comment]
@Ajiva-D Not in squares:
![Screen Shot 2022-08-15 at 5.34.48 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/896fbfb1-1fe1-4e6f-b827-2f847767eacd)
![Screen Shot 2022-08-15 at 5.34.58 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/cafb53ef-a8ba-40cd-bc0b-dc5b72117e54)
![Screen Shot 2022-08-15 at 5.35.18 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/950c9414-4db2-4066-9d13-4e8c2c53cf3d)
