### ISSUE TITLE
[bug] token select - part of selection area is not responsive to clicks

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#917]
Observed: When clicking a token in the token select modal, only clicking on the name of the token will allow the selection to be registered, and clicking outside of the name in the same highlighted section does nothing.

Expected behavior:
When I click/tap on the row of the token in the select menu,  it should select the token clicked/tapped.

![Screen Shot 2022-09-24 at 3.40.02 AM.png](https://images.zenhubusercontent.com/603eb2a37ac89a384f4c4843/a909ece6-2758-4970-a7e6-dd017de8884f)

**Comment by arne-z** [comment]
Todo Isolate this out of the Refactor Branch.
