### ISSUE TITLE
Newsletter booster for our Mainsite (Desktop & Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/workspace#919]
## Description
To boost our email sign-up, we are integrating a popover upon landing on the Mainsite. This popover can be triggered by the top nav button as well. Please look at the reference image below. 
​
## Specific Acceptance Criteria
- Layout and functions of the popover (Desktop and Mobile)
- Add the "Newsletter Sign up" button to the top nav (Desktop and Mobile)
- The popover should be triggered 5 seconds after the website is fully loaded (Desktop and Mobile)
- If the user clicks on our feature video, the popover should be presented 5 seconds after the video has been paused (Desktop and Mobile)
- We agreed to keep a tracker in the localStorage, which we set to true after the first time the modal opens (Desktop and Mobile)

## Resources
Ask the PM

## General Development Requirements
_These are our general requirements that don't change from ticket to ticket._
- Clean, lean, and organized code practices
- Spacings, colors, effects, and fonts should try to match our Figma design and communicate if there are any questions through Slack or comment under this ticket.
- This page and the entire UX flow should be adaptive with fluid transition across all desktop and mobile browsers.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.), especially on PC/android.

## Image References
![Screen Shot 2022-10-19 at 12.08.59 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ee40b3cd-59f3-46fb-ae81-56012e01554e)
![Screen Shot 2022-10-19 at 12.11.45 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/862af9cf-319b-4c4c-aa75-8ff367298631)
![Screen Shot 2022-10-19 at 12.29.43 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8d37213f-c675-4c45-b9db-3edb47b6911d)
![Screen Shot 2022-10-19 at 12.29.50 PM.png](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/8685af8e-eb52-471d-95f5-d87feba6ae1e)

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO 
https://popcorn-network-git-feat-newsletter-update-popcorn-dao.vercel.app/

**Comment by oluwatunmiisheii** [comment]
@FanFanDAO 
https://popcorn-network-git-feat-newsletter-update-popcorn-dao.vercel.app/

**Comment by FanFanDAO** [comment]
@arne-z This looks good to me and is ready for code check.
